### ISSUE TITLE
Unsupported grep -P option on Mac OS

### ISSUE THREAD

**Issue by mbroadhead** [jeffreytse/zsh-vi-mode#1]
Hi,
Thanks for authoring this plugin.
Mac OS uses BSD grep rather than GNU grep. Because of this, grep's `-P, --perl-regexp` option is not available on Mac OS . This causes a bunch of error lines to be output every time you start a new shell with this plugin enabled:
`usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]`

Here are a few options to support Mac OS:
 - Option #1: Use `grep` option `-E, --extended-regexp` rather than `-P, --perl-regexp`.
 - Option #2: Check for MacOS and if so use perl instead of grep. See [stackoverflow.com](https://stackoverflow.com/questions/16658333/grep-p-no-longer-works-how-can-i-rewrite-my-searches) for details on converting a grep call to a perl equivalent.

I'll look into this further when I get a chance.

My OS:
```
~ sw_vers
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

**Comment by jeffreytse** [comment]
Hi @mbroadhead 

Hope you have a nice day. Also, thanks for your good help and support on this plugin.

Thanks and regards
