### ISSUE TITLE
'dw' deletes first character of the next word

### ISSUE THREAD

**Issue by ls42** [jeffreytse/zsh-vi-mode#10]
Hi,

thanks for this awesome plugin, I love the cursor transformation in different modes and increased visual feedback in visual mode. :-)

I found an oddity that appears to be a bug. I've tried to look into it myself, but `zsh-vi-mode.zsh` is a bit too much for my zsh scripting skills (although it is very well commented).

Sample string: "apple orange"

When typing `dw` at the beginning of the word **a**pple, zsh-vi-mode also removes the o **o**range. This is unexpected, both default vi-mode in zsh and also vim/vi only remove up until the next word (including whitespace), not the beginning of the next word.

`de` as a workaround doesn't work, because it leaves a whitespace which `dw` usually would remove as well.

#### Input

`apple orange"

#### Action

`dw` while cursor is on `a` of apple

#### Expected Result

`orange`

#### Actual Result

`range`

**Comment by jeffreytse** [comment]
Hi @ls42 

Firstly thanks for your detailed description about the bug and I have confirm this bug. I will figure out this issue asap, and welcome to star this project for further updates.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @ls42 

🎉 Here is a good news! This issue has been addressed and fixed, please update it and have a try.

Thanks and regards

**Comment by ls42** [comment]
That is amazing, thank you so much! Tested it, working perfectly now. Have a great day 👋

**Comment by jeffreytse** [comment]
Hi @ls42 , 😃 Also hope you have a great day! And hope this plugin could help you work better.
