### ISSUE TITLE
Custom escape key doesn't work well with zsh-autosuggestions

### ISSUE THREAD

**Issue by Asocia** [jeffreytse/zsh-vi-mode#102]
I'm using `kj` for switching from insert mode to normal mode.
```
ZVM_VI_INSERT_ESCAPE_BINDKEY=kj
```
When I type `k` in insert mode, cursor waits for a second before actually writing `k` to the terminal. This is just like how it works in vim. But this doesn't work well with `zsh-autosuggestions`. Consider that following entry is in my history: `ssh desktop`.

When I type `ssh des`, I see something like this in my terminal (the bold part is coming from autosuggestions):

$ ssh des**ktop**

I add one more letter by typing `k`. Normally I would expect to see something like this:

$ ssh desk**top**

But instead, I get:

$ ssh desk**ktop**

The `k`s are doubled. This is frustrating because I generally type `ssh desk` then hit `^f` to accept the suggestion and this ends up with a wrong command: `ssh deskktop`

**Comment by jeffreytse** [comment]
Hi @Asocia 

Thanks for the reporting, I will try to fix this issue as soon as possible. And welcome to star this project for further update in the future.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @Asocia 

Thanks for your patience. This issue has been settle down, please update your plugin to the latest version and check again.

Thanks and regards

**Comment by Asocia** [comment]
I just checked out to master and I can confirm that it works. Thank you very much for the quick action!
