### ISSUE TITLE
Sometimes failed to enter Visual mode

### ISSUE THREAD

**Issue by androidfans** [jeffreytse/zsh-vi-mode#103]
![V](https://user-images.githubusercontent.com/6452650/118112986-4b459c00-b418-11eb-8781-3ed375d11e46.gif)
repro step :
1. `exec zsh` to init
2. type one character which can be auto-suggested
3. type right arrow to accept suggestion
4. esc to enter nomal mode
5. `b` to go back a word
6. try `v`. and it will not work
note : step 4 and step 5 must be quick

**Comment by jeffreytse** [comment]
Hi @androidfans 

Thanks for the reporting, this issue has been addressed and settled down. Please update your plugin to the latest version and check again.

Thanks and regards

**Comment by androidfans** [comment]
will not repro
