### ISSUE TITLE
`gg` will jump to first item in history in multi line command

### ISSUE THREAD

**Issue by androidfans** [jeffreytse/zsh-vi-mode#105]
in normal mode and in a multi line .
when cursor in the first line ,  type `gg` . will switch to the first command in history.
Is this by design?

**Comment by jeffreytse** [comment]
Hi @androidfans 

It's designed by the default vi keybindings (i.e. `bindkey -v`), not binding by this plugin.

Thanks and regards

**Comment by androidfans** [comment]
Ok, IC.  Sometimes  it will cause that i lose my current editing state.
