### ISSUE TITLE
Enter insert mode by default on new prompt

### ISSUE THREAD

**Issue by YodaEmbedding** [jeffreytse/zsh-vi-mode#110]
## General information

<details>
<summary>General information details</summary>

- Terminal program: alacritty
- Operating system: Arch Linux
- ZSH framework: zinit
- ZSH version: 5.8
- ZVM version: latest probably... is there a terminal command that can be used to determine this?

</details>

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program

## Problem description

Cursor stays in normal mode after hitting Ctrl-C.
This makes it difficult to use keybindings such as Ctrl-R.

## Reproduction steps

1. Enter normal mode.
2. Hit Ctrl-C.
3. Hit Ctrl-R.

## Expected behavior

Enter insert mode by default on new prompt.

---

P.S. There is a slight typo in the issue template ("General infomation").

**Comment by jeffreytse** [comment]
Hi @YodaEmbedding 

Thanks for the issue and the report on typo of issue template, I think your issue is related to the [command line initial mode](https://github.com/jeffreytse/zsh-vi-mode#command-line-initial-mode). By default, it's starting with last mode.

Thanks and regards

**Comment by danihodovic** [comment]
Exactly what I was looking for. Very interesting plugin @jeffreytse !

**Comment by jeffreytse** [comment]
@danihodovic Thanks for your support to this project. I hope you have a good experience in using this plugin. : )

**Comment by danihodovic** [comment]
@jeffreytse Sometimes I get an error with `command not found: fzf`

Here is my setup

```
function zvm_after_init() {
  source ${HOME}/.fzf.zsh
  source ${HOME}/.dotfiles/fzf-helpers.zsh
  source ${HOME}/.dotfiles/zsh_key_bindings.zsh
}
```

`${HOME}/.dotfiles/fzf-helpers.zsh` is properly sourced, but not fzf.zsh. Any idea why that may be?

I can reproduce the problem by opening a new prompt and pressing enter to trigger a new line very quickly.

**Comment by jeffreytse** [comment]
@danihodovic, could you have a check where a fzf command is called in your script during you stroking enter key? I will help you settle down this issue as soon as possible.

**Comment by danihodovic** [comment]
The contents of `~/.dotfiles/fzf-helpers.zsh`

```
bindkey -M vicmd '^r'   fzf-history-widget
bindkey -M viins '^r'   fzf-history-widget
```

**Comment by jeffreytse** [comment]
@danihodovic  Could you open a new issue, in case someone also meets the same issue in the future?

**Comment by jeffreytse** [comment]
@danihodovic I haven't seen the new issue created, to help you asap, here is my idea on this issue. I think this issue was caused by [the lazy keybindings feature](https://github.com/jeffreytse/zsh-vi-mode#lazy-keybindings). Accordingly, all the keybindings under normal mode (i.e. vicmd) should be bound after first time entering normal mode. In other words, you should use `zvm_after_lazy_keybindings`, see [here](https://github.com/jeffreytse/zsh-vi-mode#custom-widgets-and-keybindings). Another solution is turn off the lazy keybindings feature by setting the option `ZVM_LAZY_KEYBINDINGS` to `false`

**Comment by danihodovic** [comment]
`zvm_after_lazy_keybindings` seems to work!

**Comment by jeffreytse** [comment]
Hi @YodaEmbedding , has your issue be settled down? Feel free to reply here if you still got some problems. : )

**Comment by YodaEmbedding** [comment]
Seems to work, thanks!

```zsh
zinit light jeffreytse/zsh-vi-mode
ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
```

NOTE: `$ZVM_MODE_INSERT` is only defined after `zsh-vi-mode`.

**Comment by jeffreytse** [comment]
@YodaEmbedding , now the latest commit 8419488112dc861594c0301dabeb05d2ce0e1be1 has provided an unified configuration function for users, for the detail you can refer to [here](https://github.com/jeffreytse/zsh-vi-mode#configuration-function).

**Comment by danihodovic** [comment]
@jeffreytse I disabled the plugin after a day - I found it to be pretty slow / laggy compared to the built in vi mode. Is there any way to speed the plugin up?

**Comment by jeffreytse** [comment]
> @jeffreytse I disabled the plugin after a day - I found it to be pretty slow / laggy compared to the built in vi mode. Is there any way to speed the plugin up?

@danihodovic  , thanks for your report, which part do you feel slow/laggy? And could you try to use another readkey engine `ZLE`, see [here](https://github.com/jeffreytse/zsh-vi-mode#readkey-engine).

**Comment by danihodovic** [comment]
I'll give it another try in a week

**Comment by jeffreytse** [comment]
> I'll give it another try in a week

Thanks, and feel free to reply here if you meet any problem.
