### ISSUE TITLE
zsh-vi-mode overwrites my personal bindkey customizations 

### ISSUE THREAD

**Issue by haberdashPI** [jeffreytse/zsh-vi-mode#112]
## General information

- Terminal program: iTerm 3.4.8
- Operating system: macOS BigSur 11.2.3
- ZSH framework: oh-my-zsh
- ZSH version: 5.8
- ZVM version: 8.4.0
-->

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program 

## Problem description

Calls to `bindkey` in .zshrc do not work in normal or insert mode after installing zsh-vi-mode. 

## Reproduction steps

1. Add a bindkey statement to zshrc after calling `source $ZSH/oh-my-zsh.sh` (e.g. `bindkey '\e;' autosuggest-accept` with `zsh-autosuggestions` installed.
2. Try to use the bound key
3. The bound key will not register

## Expected behavior

I should be able to customize key combinations with `bindkey` somewhere in my zshrc script and zsh-vi-mode should not override them. (Specifically, I would expect insert mode to leave most keybindings untouched).

**Comment by haberdashPI** [comment]
I would note, although the README does explain something about using "zvm_bindkey <keymap> <keys> <widget>" there is not a very good working minimal example of how to set this up if all I want to do is make sure my existing keybindings work in insert mode. (There's something about widgets, which I don't really care about).

**Comment by jeffreytse** [comment]
Hi @haberdashPI 

Thanks for the issue. I think this is an issue about overwriting keys, and you can check issue #24 at first. And welcome to get back here for next step.

Thanks and regards

**Comment by haberdashPI** [comment]
Thanks for directing me there: might be worth changing the title there to identify it as a more general problem.

**Comment by jeffreytse** [comment]
Is it you want to bind <kbd>ESC</kbd> + <kbd>;</kbd> to the widget `autosuggest-accept`, but not working?

**Comment by haberdashPI** [comment]
That was the original issue yes. With the fix mentioned in #24, this now works.

**Comment by jeffreytse** [comment]
@haberdashPI  That's great, to hear that you have solved this problem smoothly.
