### ISSUE TITLE
Incompatible with fzf-tab

### ISSUE THREAD

**Issue by enricofadly** [jeffreytse/zsh-vi-mode#114]
## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program 

## Problem description
I tried installed this zsh-vi-mode through the zimfw and manual but It make the fzf-tab become weird behaviour (the fzf-tab completion not working), I already tried https://github.com/jeffreytse/zsh-vi-mode/issues/4 and still not working
![fzf-tab not working](https://user-images.githubusercontent.com/50710692/124601181-1eeb5080-de9a-11eb-8af3-8a7122cf98b5.png)

Zsh-vi-mode incompatible with fzf-tab , 

## Reproduction steps

1. Install through zimfw or manual sourcing
2. put the zvm_after_init_commands+=('[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh') on .zshrc
3. tab completion not working after i installed it (i done the terminal restart too)

## Expected behavior
This is the fzf-tab before i install the zsh-vi-mode
![Expected fzf tab behaviour](https://user-images.githubusercontent.com/50710692/124601340-4e01c200-de9a-11eb-954d-d3866121c389.png)

**Comment by jeffreytse** [comment]
Hi @enricofadly 

Can I confirm that the plugin you are talking about is [Aloxaf/fzf-tab](https://github.com/Aloxaf/fzf-tab)?

Thanks and regards

**Comment by enricofadly** [comment]
> Hi @enricofadly
> 
> Can I confirm that the plugin you are talking about is [Aloxaf/fzf-tab](https://github.com/Aloxaf/fzf-tab)?
> 
> Thanks and regards

Yes sir it is,

and thanks for making this amazing software, I just hope it would work with fzf-tab too

**Comment by jeffreytse** [comment]
@enricofadly , you're welcome. Also thanks for your support to this plugin. Welcome to star this project for further updates in the future. I will try to settle this issue as soon as possible.

**Comment by roosta** [comment]
Just wanna chime in with the unhelpful comment "it works here". I use zplug instead of zimfw to manage my plugins, other than that I don't really have anything special in my config. I recall having some issues with load order with some plugins, but when I tried moving fzf-tab, it still worked fine. Other than that I got nothing, but I would maybe start looking at zimfw.

**Comment by enricofadly** [comment]
> @enricofadly , you're welcome. Also thanks for your support to this plugin. Welcome to star this project for further updates in the future. I will try to settle this issue as soon as possible.

Ok sir, glad to know ur working on this,  i already starred it tho, thanks sir

**Comment by enricofadly** [comment]
> Just wanna chime in with the unhelpful comment "it works here". I use zplug instead of zimfw to manage my plugins, other than that I don't really have anything special in my config. I recall having some issues with load order with some plugins, but when I tried moving fzf-tab, it still worked fine. Other than that I got nothing, but I would maybe start looking at zimfw.

Glad to know it could still work with fzf-tab, im looking around the zplug might be found something useful,

Thanks for letting me know this sir

**Comment by jeffreytse** [comment]
@enricofadly I just have a test on the `fzf-tab` within `zinit` plugin manager, it totally work well without the issue you mentioned.

**Comment by enricofadly** [comment]
> @enricofadly I just have a test on the `fzf-tab` within `zinit` plugin manager, it totally works well without the issue you mentioned.

Ok sir that cleared half the issue that its not on fzftab and zsh vi mode issue, ill try issue the zimfw then, thanks sir for ur working and i close this issue, 

Thanks a lot

**Comment by jeffreytse** [comment]
Hi @enricofadly 

Here is the solution to make `fzf-tab` work within `zimfw`:

1. Add `zmodule Aloxaf/fzf-tab` to your `.zimrc`
2. Add `zvm_after_init+=('source ${ZIM_HOME}/modules/fzf-tab/fzf-tab.zsh')` to your `.zshrc`
3. Restart your terminal

Hope you have a good experience!

Thanks and regards

**Comment by enricofadly** [comment]
> Hi @enricofadly
> 
> Here is the solution to make `fzf-tab` work within `zimfw`:
> 
> 1. Add `zmodule Aloxaf/fzf-tab` to your `.zimrc`
> 2. Add `zvm_after_init+=('source ${ZIM_HOME}/modules/fzf-tab/fzf-tab.zsh')` to your `.zshrc`
> 3. Restart your terminal
> 
> Hope you have a good experience!
> 
> Thanks and regards

aye aye sir that's working sir.
thanks so much sir and thanks to put effort to fix my problem sir I hope this project get bigger and bigger sir

**Comment by cathaysia** [comment]
This issuse can be fixed by zinit's [turbo mode](https://github.com/zdharma/zinit#turbo-and-lucid). Here is a way to fix this: https://github.com/zdharma/history-search-multi-word/issues/19#issuecomment-897427291

**Comment by tjex** [comment]
having the same problem, but unfortunately [the fix](https://github.com/jeffreytse/zsh-vi-mode/issues/114#issuecomment-874902399) didnt work for me. Will keep looking and post back for other use cases like mine.
