### ISSUE TITLE
CURSOR COLOR

### ISSUE THREAD

**Issue by HsunGong** [jeffreytse/zsh-vi-mode#116]
## Basic examination

iterm

can we change the cursor color like
```
RED="\e[31m"
NOCOLOR="\e[0m"
ZVM_NORMAL_MODE_CURSOR=$RED$ZVM_CURSOR_BLOCK$NOCOLOR
```

**Comment by jeffreytse** [comment]
Hi @HsunGong 

For the custom cursor color, currently, you can follow below snippet:

```zsh
# This function will be automatically executed by the plugin
zvm_before_init() {
  local ncur=$(zvm_cursor_style $ZVM_NORMAL_MODE_CURSOR)
  local icur=$(zvm_cursor_style $ZVM_INSERT_MODE_CURSOR)

  ZVM_INSERT_MODE_CURSOR=$icur'\e\e]12;red\a'
  ZVM_NORMAL_MODE_CURSOR=$ncur'\e\e]12;#008800\a'
}
```

Hope the code snippet can help you and welcome to star this project for further updates in the future. : )

Thanks and regards

**Comment by daniel-careaccess** [comment]
This changes the blinking behavior. Now the cursor does not blink. In iTerm2 I have to change the cursor settings to make it blink again. Not sure how to do it with integrated terminal in VS Code.
