### ISSUE TITLE
Cursor Error when switch window

### ISSUE THREAD

**Issue by HsunGong** [jeffreytse/zsh-vi-mode#117]
## General information

iterm 3.4.3
zsh5.8
os macos
tmux 2021
## Basic examination

When open 2 terminal window in tmux,
In first terminal, we use zsh with vi-insert mode;
In the second terminal, we then open a vim window;
Found that the vim cursor is changed based on the first window, shown in the picture.

![image](https://user-images.githubusercontent.com/32933986/126091066-ff6399f8-b2d5-4ece-8ee4-df83403c1136.png)

## Expected behavior

In vim window, we want block cursor rather than underline/beam.

## reproduction

1, `ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BEAM` or `$ZVM_CURSOR_UNDERLINE`

2, tmux with 2 panes in ONE window.

3, in pane ONE: toggle insert mode in zsh-vi-mode
![image](https://user-images.githubusercontent.com/32933986/126091998-740db437-8d1d-4410-b344-97f8c86dd02a.png)

4, in pane TWO: use vim to open a file(no mode requirements<INSERT/NORMAL> is ok).
![image](https://user-images.githubusercontent.com/32933986/126092013-65c874be-c5de-4725-a3e6-fef1ab3485d2.png)

5, see vim file: the cursor is changed to BEAM or UNDERLINE as the picture.

![image](https://user-images.githubusercontent.com/32933986/126091973-915876da-565c-48e1-9003-c4dbed42dcab.png)

6, if does not reproduced, use this:

enter pane ONE: enter insert mode(to get underline/beam)
reenter pane TWO with vim: find underline/beam in vim.

**Comment by jeffreytse** [comment]
@HsunGong, this issue is the same as another issue #11.

**Comment by HsunGong** [comment]
Thanks.
