### ISSUE TITLE
zsh raise parse error when installed in cluster

### ISSUE THREAD

**Issue by yihengwuKP** [jeffreytse/zsh-vi-mode#119]
## General information

- Terminal program: xterm, tmux
- Operating system: Scientific Linux release 7.4 (Nitrogen) 
- ZSH framework: oh-my-zsh
- ZSH version: 5.0.2 (x86_64-redhat-linux-gnu)
- ZVM version: 0.8.4 (most updated github version)

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program: both xterm and tmux won't work

## Problem description

I installed `zsh-vi-mode` both locally and remotely (installed by adding as a zsh custom plugin), locally I use manjaro and it works like a charm; but remotely after I installed the plugin and `source ~/.zshrc` and re-login, a error was thrown by zsh 
```bash
/home/myname/.oh-my-zsh/custom/plugins/zsh-vi-mode/zsh-vi-mode.zsh:410: parse error near `]]'
```
for the behaviour: the cursor remains to be block rather than line, I guess of course the plugin can't be successfully loaded after throwing this error.

## Reproduction steps

1. `git clone https://github.com/jeffreytse/zsh-vi-mode $ZSH/custom/plugins/zsh-vi-mode`
2. add `plugins=(git zsh-vi-mode)` to my .zshrc
3. `source ~/.zshrc`
4. re-login to the cluster

## Expected behavior
it should be working like my local computer... Do this error help? Is it uncompatible with this old version of zsh?

**Comment by jeffreytse** [comment]
Hi @yihengwuKP 

Thanks for your reporting, as you said, I also think it could be the issue of the old version of ZSH, could you update your ZSH and try again?

Thanks and Regards

**Comment by yihengwuKP** [comment]
Hi @jeffreytse, I am trying to update the zsh in the cluster, however since I don't have root access, it's a bit tricky. Right now I downloaded zsh-5.8 and build from source in my home directory. But naively `/home/myname/bin/zsh` and `source ~/.zshrc ` didn't work for the plugin, like nothing happens. Do you know how to easily test if this zsh-5.8 is compatible with your plugin or not, without setting this zsh-5.8 to the default shell? (Because setting that to default seems to be tricky also without root)

**Comment by jeffreytse** [comment]
Hi @yihengwuKP, I use `5.8` currently, and it works perfectly, `5.0.2` was released on 2012. I will try to test the compatibility on `5.0.2`, thanks for your information.

**Comment by jeffreytse** [comment]
@yihengwuKP According to my checking, your zsh version should be `>=5.1.0`.

**Comment by yihengwuKP** [comment]
Hi @jeffreytse Thank you for your checking! I'll contact IT service to see if I can have an updated zsh on cluster! Feel free to close this if you wish

**Comment by jeffreytse** [comment]
@yihengwuKP, you're welcome, I'm waiting for your updating.

**Comment by yihengwuKP** [comment]
Hi @jeffreytse I obtained zsh-5.8 in my home directory, and once that's loaded all the problems are solved! Thank you for your help along this! (Just note here for other people experiencing the same issue, you could download and build zsh following this [procedure](https://stackoverflow.com/questions/15293406/install-zsh-without-root-access/15293565), and the loading process could be as simple as, adding 
```zsh
if [[ $ZSH_VERSION = "5.0.2" ]]; then 
    exec /home/myname/bin/zsh -l
fi
```
, without the if this would load zsh in an infinite loop because the new version of zsh would also try to read zshrc)

**Comment by jeffreytse** [comment]
HI @yihengwuKP I am very happy to hear that you have successfully solved this problem and shared the solution. Hope you have a good day!
