### ISSUE TITLE
Normal mode in IntelliJ terminal hides characters

### ISSUE THREAD

**Issue by stutterrrrer** [jeffreytse/zsh-vi-mode#120]
Using the terminal emulator by IntelliJ.
Whenever I enter normal mode to navigate, all the characters that had the block cursor fallen on them would be hidden,
and only when I press ⇧A to enter insert mode will the characters re-appear.

## Basic examination

- [ x ] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [ x ] I have the latest version of zsh-vi-mode
- [ x ] I have tested with another terminal program (the problem doesn’t happen with iTerm2 or Terminal)

## Reproduction steps

1. Use IntelliJ Terminal with zsh-vi-mode
2. Enter Normal mode and move around
3. see the characters disappear under cursor

## Expected behavior
characters not disappearing under block cursor of normal mode.

https://user-images.githubusercontent.com/38461291/131595778-b639740a-0d6a-4e78-942b-000cb79a107f.mov

**Comment by jeffreytse** [comment]
Hi @stutterrrrer 

Thanks for your reporting. I will work on this issue as soon as possible.

Thanks and Regards

**Comment by stutterrrrer** [comment]
Of course man, take your time;
I wasn’t even sure if this issue falls within your jurisdiction
nor was I expecting you to come back to me so soon;
gonna take this opportunity and say thanks for this wonderful plugin!

**Comment by jeffreytse** [comment]
Hi @stutterrrrer 

Thanks for your patience, now this issue has been addressed and fixed. Please update to the latest version and try again.

Thanks and Regards

**Comment by stutterrrrer** [comment]
Hi, thanks for the speedy response!
but I’m a newbie to the whole programming thing… How do I find the updated version to download?
I installed ZVM from Homebrew, and it’s not showing that any plugins are in need of update..
sorry if this is a dumb question

**Comment by jeffreytse** [comment]
Hi, you can follow the instructions on [manual installation](https://github.com/jeffreytse/zsh-vi-mode#manually), use `git` to clone this repository.

**Comment by stutterrrrer** [comment]
Done that, it’s fixed! thanks so much.
While I have you here, I also want to map ‘v’ to escape visual mode, just like how ‘v’ in visual mode behaves in vim.
but it doesn’t seem to work; 
I’ve modified line 3307 to ” zvm_bindkey visual ‘e’ zvm_vi_edit_command_line “ so that ‘v’ won’t be used to open vim, 
and changed line 56 to “ZVM_VI_VISUAL_ESCAPE_BINDKEY=v”

‘e’ key works as expected and opens vim, but ‘v’ just turns the block cursor into an underline cursor, while still remaining in visual mode.

Should I create a separate issue for this with screen capture attached, or is ZVM not supposed to work the way I wanted?

**Comment by jeffreytse** [comment]
Hi @stutterrrrer currently you can not use `v` to escape out from Visual mode, however, you can use `V` to escape out from Visual Line mode, 
you can use `Ctrl-[` alternatively. Welcome to star this project for further updates in the future.

**Comment by stutterrrrer** [comment]
understood. Thanks for all your hard work!
I’ll close the issue now

**Comment by jeffreytse** [comment]
@stutterrrrer You're welcome, hope you have a good day! : )

**Comment by stutterrrrer** [comment]
Hi @jeffreytse , sorry to bother you again,
but on my end it seems the bug is fixed for the terminal,
but when I open up tmux, the issue persists…
I’ve included a screen recording here:

https://user-images.githubusercontent.com/38461291/131814885-9f4ad530-e398-4154-b8b9-fbbbc0fd62c8.mov

**Comment by jeffreytse** [comment]
Hi @stutterrrrer 

This issue has been addressed and settled down, please update your plugin to the latest version, and try again.

Thanks and Regards

**Comment by stutterrrrer** [comment]
Got it!  Thanks so much.
