### ISSUE TITLE
Backspace still delete characters in normal mode

### ISSUE THREAD

**Issue by pingshunhuangalex** [jeffreytse/zsh-vi-mode#13]
When in normal mode, hitting backspace still allow users to delete characters which is not the right behaviour in Vim.

**Comment by jeffreytse** [comment]
Hi @pingshunhuangalex 

Thanks for you reporting, this plugin handled the backspace with the same behavior in Vim. Could you provider me further instructions for digging this problem?

Thanks and regards

**Comment by pingshunhuangalex** [comment]
Step to reproduce:
- start terminal with the plugin
- type some random stuff in the command line
- hit `esc` to enter normal mode (from insert mode)
- hit `backspace` a couple of times

Result:
The characters are deleted starting from the second last position (due to going into normal mode)

What's expected (behaviour in Vim)
The cursor position should start to move to the left character by character but nothing should be deleted

**Comment by pingshunhuangalex** [comment]
Not sure what I did today, but I also got stuck in some weird state that behaved like insert mode but with a normal mode cursor. Plus, I can't find a way to get out of it and ended up restarting the terminal. Haven't found the pattern to reproduce it.

**Comment by jeffreytse** [comment]
Hi @pingshunhuangalex, thanks for your reporting, I will pay attention to this issue.

**Comment by jeffreytse** [comment]
Hi @pingshunhuangalex 

About the below issue, maybe it is the same with  #26 #27, I think you can have a look.

> Not sure what I did today, but I also got stuck in some weird state that behaved like insert mode but with a normal mode cursor. Plus, I can't find a way to get out of it and ended up restarting the terminal. Haven't found the pattern to reproduce it.

**Comment by pingshunhuangalex** [comment]
I can definitely reproduce the above 2 bugs. Maybe they are the culprit, or maybe typing other characters will also stick things in limbo. Happy to close the ticket for now and will keep an eye on it after the update. Thanks for addressing the issue.
