### ISSUE TITLE
fzf keybindings not working with zsh-vi-mode

### ISSUE THREAD

**Issue by Tummetott** [jeffreytse/zsh-vi-mode#137]
## General information

- Terminal program: iTerm 3.4.11
- Operating system: MacOS 10.15.7 (Catalina)
- ZSH framework: zgen, oh-my-zsh
- ZSH version: 5.8
- ZVM version: latest

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program: Alacritty

## Problem description

In my zshrc, i have the following command after the plugin definition with zgen:
``source /usr/local/opt/fzf/shell/key-bindings.zsh``
This enables key-bindings for fzf, so i can press e.g. CTRL-r and get the fzf command history search instead of the normal backward search. It's working perfect until I put the ZVM plugin in zgen's plugin list. 
However, when I run the source command as interactive command in my zsh, the keybinding is back.

Then I tried sourcing anything at the end of my zshrc -- it has no effect. Whenever I remove the plugin, the normal behaviour is back. Is it possible that the plugin somehow uses the CTRL-r shortcut?

EDIT: I realised, that i have the same problem with `softmoth/zsh-vim-mode` once I turn on mode sensitive cursor styling

## Reproduction steps
1. Download zgen: `git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"`
2. Install fzf with brew (or other plugin manager, then the path changes)
2. Copy the following zshrc:
```
source "${HOME}/.zgen/zgen.zsh"
zgen load jeffreytse/zsh-vi-mode
source /usr/local/opt/fzf/shell/key-bindings.zsh
```
3. Restart terminal
4. Press CTRL-r

## Expected behavior
fzf history search pops up

## Actual behavior
zsh's backward search pops up

**Comment by jeffreytse** [comment]
Hi @Tummetott 

Please read issue #24 

Thanks and Regards

**Comment by Tummetott** [comment]
Oh i'm so sorry. I thought I checked the issues. Thanks a lot! This plugin is amazing. Just starred it!

**Comment by jeffreytse** [comment]
@Tummetott You're welcome, hope you have a good day! : )
