### ISSUE TITLE
Start zsh in normal mode

### ISSUE THREAD

**Issue by pingshunhuangalex** [jeffreytse/zsh-vi-mode#14]
Atm when zsh is initialised with the plugin, it automatically goes to insert mode. It kinda make sense in a command-line context but just wondering if it's possible to start zsh with the normal mode which matches Vim's behaviour better.

**Comment by jeffreytse** [comment]
Hi @pingshunhuangalex 

As you said, it automatically goes to insert mode when zsh is initialised, I will add an option for initial mode, and I will update here for this new feature.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @pingshunhuangalex 

🎉  Firstly thanks for your patience. Now this plugin has support setting the initial mode feature, the feature detail you can open this issue #22. Also welcome to [support my open source work](https://github.com/sponsors/jeffreytse)! Thank you!

Thanks and regards
