### ISSUE TITLE
Custom escape keys breaks CTRL-r history search

### ISSUE THREAD

**Issue by redpublic** [jeffreytse/zsh-vi-mode#145]
## General information
Custom escape keys breaks `CTRL-r` history search.

- Terminal program: iTerm2 3.4.12
- Operating system: macOS Big Sur 11.6
- ZSH framework: oh-my-zsh
- ZSH version: 5.8
- ZVM version: last master

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [ ] I have tested with another terminal program 

## Problem description
If you redefine `ZVM_VI_INSERT_ESCAPE_BINDKEY`, it's not possible to enter first character of escape key in `CTRL-r` history search. You exit the search mode.

## Reproduction steps

1. Redefine with `ZVM_VI_INSERT_ESCAPE_BINDKEY=fd`
2. Enter history search mode with `CTRL-r`
3. Enter `f` character
4. Search mode is cancelled, `f` is inserted in command line

## Expected behavior

`CTRL-r` history search works as usually

**Comment by jeffreytse** [comment]
Hi @redpublic 

Thanks for your reporting, I will try to fix this issue as soon as possible, please be patient. : )

Thanks & Regards

**Comment by jeffreytse** [comment]
Hi @redpublic 

Thanks for your patience, now this issue has been addressed and fixed. Welcome to update to the HEAD version to give it a glance. : )

Thanks & Regards

**Comment by redpublic** [comment]
Hi @jeffreytse,

Thanks a lot, it works!
