### ISSUE TITLE
Partial history search from "zsh-autosuggestions" is overidden

### ISSUE THREAD

**Issue by pingshunhuangalex** [jeffreytse/zsh-vi-mode#15]
I use `zsh-autosuggestions` for auto-complete which provides a very neat partial search capability. However, with the installation of `zsh-vi-mode`, partial search no longer works and was forcefully replaced with jumping among historical commands.

Steps to reproduce:
- run 2 commands such as `test working 1` and `test not working 2`
- when `zsh-vi-mode` is not installed, typing `test` and pressing up/down arrow will circle historical commands that start with `test`
- when `zsh-vi-mode` is installed, typing `test` and pressing up/down arrow will just jump to the previous/next command

Is there a way for me to get the best of both world here? Possible solutions:
- Support partial search in this plugin
- Find a way to use the existing arrow key behaviour from terminal or other plugin
- Give the option to turn off search implemented by this plugin

**Comment by jeffreytse** [comment]
Hi @pingshunhuangalex 

Thanks for your issue and currently I am a little bit busy, I will do the digging and reply you as soon as possible, please be patient.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @pingshunhuangalex 

This plugin never overwrite the keybindings on arrow keys, and the history search functionality is not from the `zsh-autosuggestions`, this commit (dfa6f0b) has added some keybindings for the partial history search. Welcome to update your plugin to it.

Thanks and regards

**Comment by pingshunhuangalex** [comment]
Thanks for the quick fix. I'm still a bit confused here.

- So the partial search may be from the terminal (I'm using Hyper) if it's not from `autosuggestion` cuz I only used `autosuggestion` and `syntaxhighlight` in my zsh.
- It wasn't supported previously cuz the arrow key was never mapped in `vi-mode`, and now with your commit, it's fixed

Did I get the relationship right? Thanks

**Comment by jeffreytse** [comment]
Hi @pingshunhuangalex 

You have got the relationship correctly, as the arrow key was never mapped, it is using the default mapping in vi mode.

Thanks and regards

**Comment by pingshunhuangalex** [comment]
Confirmed fixed. Works like a charm. Thanks

**Comment by jeffreytse** [comment]
Hi @pingshunhuangalex 

I would probably revert the bindings of Arrow Up/Down to the default, as that's what most Vi users will expect. For your reference, here is a snippet to help you reach the partial history conveniently. 

```zsh
# The plugin will auto execute this zvm_after_init function
function zvm_after_init() {
  zvm_bindkey viins '^[[A' history-beginning-search-backward
  zvm_bindkey viins '^[[B' history-beginning-search-forward
  zvm_bindkey vicmd '^[[A' history-beginning-search-backward
  zvm_bindkey vicmd '^[[B' history-beginning-search-forward
}
```

Thanks and regards

**Comment by pingshunhuangalex** [comment]
Where should I put this snippet? inside `.zshrc`?

**Comment by jeffreytse** [comment]
Hi, @pingshunhuangalex

Yes, you're right, you can put this inside `.zshrc` in order to execute this code snippet.

Thanks and regards

**Comment by pingshunhuangalex** [comment]
Adding this snippet does maintain the partial search function, but it also breaks the entire mode switching and I can't go to normal mode by pressing `esc` anymore. More precisely, pressing `esc` will give me `^[` in terminal. Commenting out the snippet fixes the issue again.

**Comment by jeffreytse** [comment]
Hi @pingshunhuangalex 

Actually, you should add these keybindings in `zvm_before_init` function, I have edited that code snippet and please try the above snippet again.

Thanks and regards

**Comment by pingshunhuangalex** [comment]
Works, thanks

**Comment by CaninoDev** [comment]
A small note:

Should you be using `oh-my-zsh` and have `history-substring-search` in your list of plugins, make sure that `zsh-vi-mode` is listed _before_ `history-substring-search` to maintain functionality. Haven't yet fully tested to see if `history-substring-search` affects other areas of `zsh-vi-mode` as I just started using this plugin. For some reason, if the order was reversed, `history-substring-search` doesn't work as expected.

**Comment by jeffreytse** [comment]
Hi @CaninoDev 

Thanks for the small note, you will be very welcome to open an issue if you meet any problem. : )

Thanks and regards
