### ISSUE TITLE
AUR packages

### ISSUE THREAD

**Issue by MonstrousOgre** [jeffreytse/zsh-vi-mode#16]
First of all, I just discovered this plugin and love it.

Since I don't use a plugin manager for zsh and didn't want to pull regularly, I created the AUR packages [zsh-vi-mode](https://aur.archlinux.org/packages/zsh-vi-mode/) and [zsh-vi-mode-git](https://aur.archlinux.org/packages/zsh-vi-mode-git/)

Maybe you could add this to the README? It currently installs to `/usr/share/zsh/plugins/zsh-vi-mode/`

And let me know if you'd rather maintain the packages yourself

**Comment by jeffreytse** [comment]
Hi @MonstrousOgre 

Thanks for your support and I love this plugin. As you said, some people may not use any one of plugin managers for zsh, so I think your request is quite helpful for lot of users. I could add this to the `README` file, and I would rather maintain the AUR packages myself for updates in future.

Thanks and regards

**Comment by MonstrousOgre** [comment]
@jeffreytse sure! Just let me know your AUR username and I'll add you as a maintainter.

**Comment by jeffreytse** [comment]
Hi @MonstrousOgre 

My AUR username is `jeffreytse`

Thanks and regards

**Comment by MonstrousOgre** [comment]
Done!

**Comment by jeffreytse** [comment]
Hi @MonstrousOgre 

I have added related installation on AUR to [README](https://github.com/jeffreytse/zsh-vi-mode#arch-linux-aur).

Thanks and regards
