### ISSUE TITLE
Conflict with Zsh-autopair

### ISSUE THREAD

**Issue by Tainted-Fool** [jeffreytse/zsh-vi-mode#185]
## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program 

## Problem description

All my plugins were working properly until I introduced this plugin into the mix. Basically, this plugin conflicts with (zsh-autopair)[https://github.com/hlissner/zsh-autopair] . When I remove this plugin `zsh-vi-mode`, `zsh-autopair` works. The autopair plugin does not get initialized if I enable this plugin.

For example as soon as I press quotation mark `"` I should get another `"` right next to the cursor i.e. autopair. However, when I enable this, the pair does not show up unless I run `source ~/.zshrc` or initialize the autopair with `autopair-init`

## Reproduction steps

1. Add this to `~/.zshrc` file:
```sh
source ~/.zsh-autopair/autopair.zsh
source ~/.zsh-vi-mode/zsh-vi-mode.plugin.zsh
autopair-init
```
2. Close terminal and re-open
3. Try to trigger autopair by typing `'`, `"`, `(`, etc.
4. Notice no pair - need to manually source or initialize autopair to fix

## Expected behavior
Autopair to trigger as soon as you open a terminal. I don't mind initializing autopair but it should do it on its own based on the `~/.zshrc` settings. Apart from that, I am loving the plugin so far! Keep up the good work 😄

**Comment by musjj** [comment]
This happens because `zsh-vi-mode` is lazy-loaded. This can cause some unpredictable things to happen, despite having the correct load order in your `~/.zshrc`.

The simplest solution is to turn off lazy-loading by doing:

```zsh
ZVM_INIT_MODE=sourcing
```

Or you can also do something like:

```zsh
zvm_after_init_commands=(autopair-init)
```

**Comment by Anomalocaridid** [comment]
For posterity and just in case it helps someone with the same problem, setting `ZVM_INIT_MODE=sourcing` didn't help, but setting `zvm_after_init_commands=(autopair-init)` did.

Also it might be helpful to set [`AUTOPAIR_INIT_INHIBIT=1`](https://github.com/hlissner/zsh-autopair#troubleshooting--compatibility-issues) so you don't initialize zsh-autopair twice.

**Comment by Tainted-Fool** [comment]
@musjj  and @Anomalocaridid suggested fixed my issue. Thank you very much for the help. You guys rock!
