### ISSUE TITLE
Mode indicator isn't updating

### ISSUE THREAD

**Issue by BerkeleyTrue** [jeffreytse/zsh-vi-mode#2]
Switching from oh my zsh vi-mode. I have a theme I've created based on keymaps. It seems that this plugin is somehow changing the keymap or preventing my theme from updating on keymap changes.

Here is the theme I'm using, pointing to the section where keymap is updated. It hooks into the precmd func.
https://github.com/berkeleytrue/dotfiles/blob/master/.config/zsh/ghanima.zsh-theme#L99

**Comment by jeffreytse** [comment]
Hi @BerkeleyTrue 

Thanks for your reporting this issue, and now this issue has been addressed and settled down.

Thanks and regards

**Comment by BerkeleyTrue** [comment]
Works!
