### ISSUE TITLE
macos can't use `Ctrl-h` to delete character on somewhere in the insert mode

### ISSUE THREAD

**Issue by hongcn5** [jeffreytse/zsh-vi-mode#201]
## General information

- Terminal program: iterm2 3.5.0beta9, mac(m1) default terminal 
- Operating system: macOS Ventura 13.1
- ZSH framework: none
- ZSH version: 5.8.1 (x86_64-apple-darwin22.0)
- ZVM version: stable 0.9.0

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program 

## Problem description

can't use `Ctrl-h` to delete character on anywhere in the insert mode after normal mode into insert mode

## Reproduction steps

1. type or paste command, such as `setopt`
2. escape from insert mode to normal mode, move the cursor to anywhere, eg: `set` | `opt`
3. and then press `a` or `A` to insert mode, use `Ctrl-h` to delete character, only can delete character after `set` 

## Expected behavior
1. type or paste command, such as `setopt`
2. escape from insert mode to normal mode, move the cursor to anywhere, eg: `set` | `opt`
3.  and then press `a` or `A` to insert mode
4. use `Ctrl-h` delete character on anywhere

## .zshrc config

zvm_before_init() {
  local ncur=$(zvm_cursor_style $ZVM_NORMAL_MODE_CURSOR)
  ZVM_INSERT_MODE_CURSOR=$ncur'\e\e]12;#929292\a'
  ZVM_NORMAL_MODE_CURSOR=$ncur'\e\e]12;#008800\a'
}
zvm_config() {
  ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
  ZVM_VI_ESCAPE_BINDKEY=jk
  ZVM_VI_HIGHLIGHT_BACKGROUND=#519e97
}
source /opt/homebrew/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh

**Comment by hongcn5** [comment]
sorry, i misunderstand the feature of shortcut 'ctrl-h'

**Comment by GiovanePS** [comment]
This exact same issue also exists in Linux. I'm using Debian 12.
