### ISSUE TITLE
zvm_config:2: command not found: zvm_cursor_style

### ISSUE THREAD

**Issue by woodnathan** [jeffreytse/zsh-vi-mode#206]
## General information

Please report the following information as possible as you can:

- Terminal program: Apple Terminal 2.13 (447)
- Operating system: CentOS Stream release 9
- ZSH framework: None, git-clone
- ZSH version: zsh 5.8 (x86_64-redhat-linux-gnu)
- ZVM version: 0.8.5

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program 

## Problem description

I setup zsh-vi-mode on macOS but kept receiving the following messages when opening a new shell:
```
zvm_config:2: command not found: zvm_cursor_style
zvm_config:3: command not found: zvm_cursor_style
```

To rule things out, I setup a CentOS VM, installed zsh and git, and then setup zsh-vi-mode according to the "Manually" instructions.
I then followed the instructions from the README under "Also, custom your colorful cursor style as below"

Now every time the shell starts I get told that `zvm_cursor_style` can't be found.

Full .zshrc:
```
# The plugin will auto execute this zvm_config function
zvm_config() {
  # Retrieve default cursor styles
  local ncur=$(zvm_cursor_style $ZVM_NORMAL_MODE_CURSOR)
  local icur=$(zvm_cursor_style $ZVM_INSERT_MODE_CURSOR)

  # Append your custom color for your cursor
  ZVM_INSERT_MODE_CURSOR=$icur'\e\e]12;red\a'
  ZVM_NORMAL_MODE_CURSOR=$ncur'\e\e]12;#008800\a'
}

source $HOME/.zsh-vi-mode/zsh-vi-mode.plugin.zsh
```

## Reproduction steps

1. git clone https://github.com/jeffreytse/zsh-vi-mode.git $HOME/.zsh-vi-mode 
2. Update .zshrc with the contents above
3. `source ~/.zshrc`

## Expected behavior
No error message.

**Comment by jeffreytse** [comment]
Hi @woodnathan 

Thanks for your issue, and this is a bug after further verification, I will fix it as soon as possible.

Thanks & Regards

**Comment by woodnathan** [comment]
I can confirm that this is now fixed. Thanks!
