### ISSUE TITLE
Visual mode highlight stuck after deleting

### ISSUE THREAD

**Issue by musjj** [jeffreytse/zsh-vi-mode#207]
## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program 

## Problem description

Visual mode's highlight doesn't go away, after deleting the selected text using `x`. The highlight will follow the cursor as if it's still in visual mode.

## Reproduction steps

1. Enter visual mode
2. Move the cursor and select a range of text
3. Delete text using `x`

## Expected behavior

Selection highlight should go away.

**Comment by jeffreytse** [comment]
Hi @musjj 

Thanks for your reporting, I will fix your issue as soon as possible. And welcome to star this project for further update in the future. : )

Thanks & Regards

**Comment by musjj** [comment]
Thanks, the commit fixed the issue for me!
