### ISSUE TITLE
Switching from visual to insert mode

### ISSUE THREAD

**Issue by TxHawks** [jeffreytse/zsh-vi-mode#208]
## General information

- Terminal program: iTerm 3.4.19
- Operating system: macOS Ventura 13.2.1
- ZSH framework: zplug
- ZSH version: 5.9
- ZVM version: 0.8.5

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program 

## Problem description

Switching from `visual` mode to `insert` mode is awkward, since you have to go through `normal` mode, and even a bit confusing, since hitting `i`, `a`, etc., in visual mode has the effect of changing the cursor, but leaves you in visual mode.

## Reproduction steps

1. In insert mode, hit `Esc` then `v` to enter visual mode
2. Hit `i`, the cursor changes
3. type `ia`, no input is entered
4. hit `l`, a letter is selected to the right

## Expected behavior
`i`, `a`, etc., should go straight into insert mode, deselecting selected text (if any)

**Comment by jeffreytse** [comment]
Hi @TxHawks 

Thanks for your reporting, I will fix your issue as soon as possible. And welcome to star this project for further update in the future. : )

Thanks & Regards

**Comment by jeffreytse** [comment]
Hi @TxHawks,

The behavior is that it should keep in the visual mode after typing `ia` sequence in real VIM accordingly.

Thanks & Regards
