### ISSUE TITLE
Pasting in visual mode 

### ISSUE THREAD

**Issue by musjj** [jeffreytse/zsh-vi-mode#212]
## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program 

## Problem description

After pasting in visual mode, normal mode is not activated.

## Reproduction steps

1. Select a text and copy it
2. Enter visual mode and select a range of text
3. Paste

## Expected behavior

Normal mode should be activated after pasting.

**Comment by jeffreytse** [comment]
Hi @musjj 

This issue has been fixed. Thanks for your reporting.

Thanks & Regards

**Comment by musjj** [comment]
Thanks, it's working for me!
