### ISSUE TITLE
prompt text color is incorrect

### ISSUE THREAD

**Issue by penglei** [jeffreytse/zsh-vi-mode#217]
![image](https://user-images.githubusercontent.com/1140325/236816045-60815679-6563-4fba-ab49-4f495a04c8f8.png)
![image](https://user-images.githubusercontent.com/1140325/236816621-41645120-b262-4919-81d0-200bac0feb09.png)

## General information

Please report the following information as possible as you can:

- Terminal program:  alacritty
- Operating system:  macOS
- ZSH framework:  no
- ZSH version: 5.9
- ZVM version: 0.9.0

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program 

## Problem description

I use starship, which has a nice feature: the part of the command that has not been entered yet is grayed out. However, when using vi-zsh-mode, the color of the command un-entered yet becomes normal white. 

## Reproduction steps

1. type `ls /etc` to save it in history
2. type 'l' =>  l
3. type 's' => ls

## Expected behavior

the `/etc` text color should be gray.

**Comment by jeffreytse** [comment]
Hi @penglei,

Thanks for your issue, and sorry for the late reply, could you try again with the latest version?

Thanks & Regards

**Comment by penglei** [comment]
> Hi @penglei,
> 
> Thanks for your issue, and sorry for the late reply, could you try again with the latest version?
> 
> Thanks & Regards

I tried the latest main branch and I think this bug still exists. 😞

**Comment by jeffreytse** [comment]
@penglei I will try to dig this issue as soon as possible, I will get back to you recently. : )

**Comment by jeffreytse** [comment]
Hi @penglei,

May I know if you are using `zsh-syntax-highlighting`?

Thanks & Regards

**Comment by penglei** [comment]
> Hi @penglei,
> 
> May I know if you are using `zsh-syntax-highlighting`?
> 
> Thanks & Regards

YES

**Comment by jeffreytse** [comment]
@penglei I think this issue related to #228, and now it was fixed by db7b7d4. Could you have a check again with the newer version?

**Comment by penglei** [comment]
@jeffreytse  Wow, it works. Thank you.
