### ISSUE TITLE
Actions like dt' or ct" don't work

### ISSUE THREAD

**Issue by YasserKa** [jeffreytse/zsh-vi-mode#218]
## General information
```
echo $TERM && kitty --version && uname -r && zsh --version && zap version
xterm-kitty
kitty 0.28.1 created by Kovid Goyal
6.3.1-arch2-1
zsh 5.9 (x86_64-pc-linux-gnu)
⚡ Zap - Version

Version: release-v1/1.2.1
Commit Hash: 2904b87 (5 hours ago)
```
## Basic examination

- [X] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [X] I have the latest version of zsh-vi-mode
- [X] I have tested with another terminal program  (Xfce4, Alacritty, wezterm)

## Problem description

Using `d` and `c` with `f` and `t` till `'` or `"` don't work as intended. Check Reproduction steps.

## Reproduction steps

The first action I did is `dt'` the second one is `ct"`
https://asciinema.org/a/56MgA9kH6nxcvHc8j4TGKxpY1

**Comment by jeffreytse** [comment]
Hi @YasserKa 

Thanks for your reporting, now this issue has been fixed, and welcome to star this project for further update in the future. 👍 

Thanks & Regards
