### ISSUE TITLE
NEX read engine throws error when a '-' follows the first character of escape bindkey

### ISSUE THREAD

**Issue by matt-simons** [jeffreytse/zsh-vi-mode#220]
## General information

Please report the following information as possible as you can:

- Terminal program: Iterm2
- Operating system: macOS 13.3.1
- ZSH framework: p10k
- ZSH version: zsh 5.9 (x86_64-apple-darwin22.0)
- ZVM version: 

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program Terminal (default)

## Problem description

When using the default readkey engine, nex, it's not possible to type 'k-' in insert mode when `ZVM_VI_INSERT_ESCAPE_BINDKEY=kk` is set. Switching to ZLE read engine fixes it `ZVM_READKEY_ENGINE=$ZVM_READKEY_ENGINE_ZLE`. Not sure whether this is the right place for this issue to be raised.

## Reproduction steps

1. set `ZVM_VI_INSERT_ESCAPE_BINDKEY=kk`
2. type 'k-' while in insert mode
3. error message is printed:
```
❯ k
zvm_readkeys_handler:zle:38: not enough arguments for -U
```

## Expected behavior

```
❯ k-
```

**Comment by jeffreytse** [comment]
Hi @matt-simons,

Thanks for your kindly reporting on the issue, and sorry for the late reply as I'm quite busy recently. Now this issue is fixed, please update to the latest version and try again. Welcome to start this project for further updates in the future. : )

Thanks & Regards

**Comment by matt-simons** [comment]
Thank you!
