### ISSUE TITLE
zsh-vi-mode breaks zsh-syntax-highlighting

### ISSUE THREAD

**Issue by tdljayden** [jeffreytse/zsh-vi-mode#228]
## General information

- Terminal program: Kitty
- Operating system: Gentoo
- ZSH framework: oh-my-zsh
- ZSH version: 5.9
- ZVM version: (not sure but it's the latest version according to oh-my-zsh)

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program  (I tested with alacritty aswell)

## Problem description

Installing and setting zsh-vi-mode in my .zshrc breaks the plugin zsh-syntax-highlighting. Shown below is an example of a terminal command before and after setting zsh-vi-mode in my config.
Before:
![image](https://github.com/jeffreytse/zsh-vi-mode/assets/110114652/4cd061fd-8180-4e3a-abee-b70573577473)
After:
![image](https://github.com/jeffreytse/zsh-vi-mode/assets/110114652/edb3ced6-761c-428d-80ad-8e62f0e4eb68)

## Reproduction steps

1. Download and install zsh-vi-mode and zsh-syntax-highlighting.
2. Enable them in your .zshrc like this: 
```
plugins=(
	zsh-vi-mode
	zsh-syntax-highlighting
)
```
3. Try typing a command with multiple arguments.

## Expected behavior

The intended behaviour should be that different commands and arguments appear in their respective colours.
Like this:
![image](https://github.com/jeffreytse/zsh-vi-mode/assets/110114652/4cd061fd-8180-4e3a-abee-b70573577473)

**Comment by Ra1ze505** [comment]
i have this problem too 😢

**Comment by jeffreytse** [comment]
Hi @tdljayden,

I've fixed the issue you mentioned. Could you try the latest version? If you still got the issue, please let me know. And welcome to star this project for further update in the future. : )

Thanks & Regards
