### ISSUE TITLE
Can't leave insert mode after typing S from normal mode

### ISSUE THREAD

**Issue by gotgenes** [jeffreytse/zsh-vi-mode#26]
When in normal mode, then typing `S`, this plugin clears the line and puts the user in insert mode, consistent with behavior described in Vim.

>```
>["x]S                   Delete [count] lines [into register x] and start                                                                        
>                         insert.  Synonym for "cc" linewise.      
>```

However, at this point, it does not seem to be possible to exit insert mode. The user is forced to hit Enter to get a new prompt. This prompt will actually start in normal mode, which is also unexpected.

I do not observe this behavior when using `cc` from normal mode. Like `S`, `cc` will clear the line's contents and put me in insert mode, however, I am able to hit `Esc` and get back to normal mode, as expected.

**Comment by jeffreytse** [comment]
Hi @gotgenes 

Thanks for your reporting this issue and the detail provided, I will fix this issue as soon as possilble. And welcome to star this project for further upadtes.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @gotgenes 

:tada: Thank you for your patience, this issue has been addressed and fixed, please update your plugin to the latest version. And welcome to star this project for further upadtes in the future.

Thanks and regards

**Comment by gotgenes** [comment]
Confirmed this is fixed in the latest version. Thank you!
