### ISSUE TITLE
Question: Does it support "redo?

### ISSUE THREAD

**Issue by zzJinux** [jeffreytse/zsh-vi-mode#272]
## General information

The README has a "Redo" feature, but I can't find how to do it or any code involved.

Thank you for the awesome plugin and devotion.

## Basic examination

- [ ] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [ ] I have the latest version of zsh-vi-mode
- [ ] I have tested with another terminal program 

## Reproduction steps

1.
2.
3.

**Comment by GiorgosXou** [comment]
It's vi-mode, you can `CTRL+R` to "redo", wdym? do you mean "repeat"?

**Comment by zzJinux** [comment]
@GiorgosXou Is `history-incremental-search-backward ` considered "redo" in this plugin? I expect `CTRL+R` to do the exact opposite of `u`.

Please let me know if I'm wrong.

**Comment by GiorgosXou** [comment]
Yes. It does the exact opposite. In which case scenario it doesn't?

**Comment by GiorgosXou** [comment]
@zzJinux If your issue was resolved, please close it.

**Comment by zzJinux** [comment]
@GiorgosXou I'm embarrassed to find that `CTRL+R` triggers fzf in my shell. After disabling fzf, `CTRL+R` turned out to behave as intended. Sorry for my carelessness!

**Comment by YodaEmbedding** [comment]
Notice `eval "$(fzf --zsh)"` binds both modes to `<C-r>`:

```zsh
bindkey -M vicmd '^R' fzf-history-widget
bindkey -M viins '^R' fzf-history-widget
```

For normal mode (`vicmd`), I remapped `^R` back to `redo`:

```zsh
zvm_bindkey vicmd '^R' redo

# Also interesting:
# zvm_bindkey vicmd 'U' redo
```
