### ISSUE TITLE
Zsh history search to zvm_bindkey

### ISSUE THREAD

**Issue by Eloquencere** [jeffreytse/zsh-vi-mode#286]
## General information

```
- Terminal program: Alacritty
- Operating system: Arch Linux 6.9
- ZSH framework: zinit
- ZSH version: 5.9.0
```

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [ ] I have tested with another terminal program 

## Problem description
I used to use zsh's completion for command history by using the keybind - bindkey '^p' line-up-or search , and another for line down, now after switching to zvm, I know that a key can be set by doing - zvm_bindkey <keymap> <keys> <widget>, so I tried that with line up search, and I am getting - line-up-or-search: function definition not found.

I even tried doing autoload -U line-up-or-search && line-up-or-search - to no avail

## Reproduction steps

1. add 
```
zvm_bindkey vicmd '^p' line-up-or-search 
zvm_bindkey vicmd '^n' line-down-or-search 
to .zshrc
```
2. pressing any of the above keys(^p, ^n) in normal or insert mode doesn't do the expected completion and raises the error

## Expected behavior
It's supposed to complete a command based on the previous commands that were run with that specific cli tool like cd, ls etc

**Comment by noahfraiture** [comment]
Hello, how did you resolve this ?

**Comment by Eloquencere** [comment]
it's done by adding the bindkey statement within a function called "zvm_after_init()" using "zvm_bindkey". The issue is that once vi mode is enabled in zsh, it wipes out all the keybinds configured before it, so keybinds that need to be used with the vi mode have to be registered once the setup is done

function zvm_after_init() {
	# Zsh-Vi-Mode
	ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
	zvm_bindkey viins '^p' line-up-or-search
        zvm_bindkey viins '^n' line-down-or-search 
}

I added this line at the end of my zshrc and it's working as expected. This function is automatically called by zvm after initialisation.

**Comment by noahfraiture** [comment]
Ok thank you
