### ISSUE TITLE
local cat alias breaks `d` in normal mode

### ISSUE THREAD

**Issue by BerkeleyTrue** [jeffreytse/zsh-vi-mode#3]
I've got `cat` aliased to `bat` locally, and it seems that cat is used internally to parse keys using the -v key which isn't supported by bat.

![image](https://user-images.githubusercontent.com/6775919/103463516-c320ee80-4ce1-11eb-8a73-8b7ee50a5770.png)

ref: https://github.com/jeffreytse/zsh-vi-mode/blob/b74c0dfc712593b14c4dff6449e58623d7dc7b8f/zsh-vi-mode.zsh#L251

Not sure if this is workable as I know it's not really standard to expect cat to be aliased. Maybe if you go for /usr/bin/cat, but then that might make it harder to support other systems...

I think I could work around by using a function that checks for valid bat args and if it finds something that won't work with bat then defer to cat.

**Comment by jeffreytse** [comment]
Hi @BerkeleyTrue

🎉 Firstly, thank you very much for your issue reporting, and now this issue has been addressed and settled down. Welcome to star this project for further features in the future.

Thanks and regards

**Comment by BerkeleyTrue** [comment]
Woah! very nice! Works like a charm. I'll be switching over now. Thanks for the hard work!
