### ISSUE TITLE
Using a to enter insert mode from empty command line triggers terminal bell

### ISSUE THREAD

**Issue by gotgenes** [jeffreytse/zsh-vi-mode#31]
When the command line is empty, after entering normal mode with `Esc`, pressing `a` to enter insert mode triggers the terminal bell.

![bell](https://user-images.githubusercontent.com/8517/109409053-19a65400-7944-11eb-9b1f-689fc186e5e4.gif)

Note that using `i` or `A` to enter insert mode does not cause the terminal bell to fire. Using `a` to enter insert mode when the command line has at least one character will also not trigger the terminal bell.

**Comment by jeffreytse** [comment]
Hi @gotgenes 

Thanks for the reporting and the issue has been addressed and fixed. Please update your plugin to the latest version.

Thanks and regards

**Comment by gotgenes** [comment]
Fix confirmed. Thanks!
