### ISSUE TITLE
Can't use c<count>, d<count>

### ISSUE THREAD

**Issue by gotgenes** [jeffreytse/zsh-vi-mode#32]
zsh-vi-mode does not seem to take `<count>` after `c` or `d` and before `<motion>`, such as `c2w` or `d2w`. It only seems to accept a count before `c` or `d`.

**Comment by jeffreytse** [comment]
Hi @gotgenes 

🎉 This issue has been addressed and fixed. Please update your plugin to the latest version.

Thanks and regards

**Comment by gotgenes** [comment]
Confirmed fixed. Thanks!
