### ISSUE TITLE
Home and Insert keys enter normal mode

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [jeffreytse/zsh-vi-mode#33]
When I press home & insert keys I enter normal mode instead of jumping ^ or $.

I checked regular `bindkey -v` and they seem to work, so I suspect somehow this plugin does some overrides.

 If this is intended, behavior option would still be preferred.

**Comment by jeffreytse** [comment]
Hi @ZeChArtiahSaher 

I have checked the issue, in fact this plugin does not override `<HOME>` and `<INSERT>`, so the behavior is the same with the default vi mode, that is `bindkey -v`. 

Thanks and regards

**Comment by ZeChArtiahSaher** [comment]
Without inspecting the issue further I found this to work:

```
zvm_bindkey viins '^[[H' beginning-of-line
zvm_bindkey viins '^[[F' end-of-line
```

in `zvm_init`

**Comment by jeffreytse** [comment]
Hi @ZeChArtiahSaher 

If you want to execute extra commands, you can see [here](https://github.com/jeffreytse/zsh-vi-mode#execute-extra-commands), the best place to put your code for your reference.

Thanks and regards
