### ISSUE TITLE
zvm_readkeys: maximum nested function level reached; increase FUNCNEST?

### ISSUE THREAD

**Issue by AckslD** [jeffreytse/zsh-vi-mode#34]
I'm sometimes randomly getting the warning/error 
```
zvm_readkeys: maximum nested function level reached; increase FUNCNEST?
```
, any idea why that could be?

**Comment by jeffreytse** [comment]
Hi @jeffreytse 

Thanks for your reporting, I will take attention to the issue. Any idea I will update here.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @AckslD 

Could you provide me some instructions to reproduce this issue?

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @AckslD 

Ok, when you or someone meet the same issue again, you and they can comment to here. And I will also pay attention to it.

Thanks and regards

**Comment by AckslD** [comment]
@jeffreytse Still not sure why but it just happened now once. I had two kitty terminals open with zsh in one and neovim in the other. While doing some stuff in neovim I got this error in the other terminal, pretty strange since I was not actually doing anything in the terminal that showed the error.

Btw, I'm using kmonad if that has anything to do with it.

**Comment by jeffreytse** [comment]
Hi @AckslD 

I have reproduced this issue and this is a bug actually.

## Reproduce

- Find a keybinding with the ctrl character, such as `^W`
- Bind a widget with the above ctrl character prefix's sequence, such as `^Ww`.
- Open the zsh again.
- Stroke `^W` and stop.
- Wait for a while and it will show the error as issue title.

**Comment by jeffreytse** [comment]
Hi @AckslD 

This issue has been addressed and fixed. Please update your plugin to the latest version.

Thanks and regards
