### ISSUE TITLE
Cursor insert mode style affects other applications

### ISSUE THREAD

**Issue by Hubro** [jeffreytse/zsh-vi-mode#35]
I enjoy using these cursor styles to clearly distinguish between normal mode and insert mode:

```
ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLINKING_BEAM
ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_BLOCK
```

However, the insert mode cursor style is inherited by other applications, and those applications don't handle switching between cursor styles when switching modes, which makes the cursor permanently stay in the insert mode style until the application is exited.

For example, try starting Vim from the terminal, or simply start bash. Inside vim or bash, the insert mode cursor is permanently active, even when switching to normal mode. This is extremely distracting.

I wish zsh-vi-mode would "reset" the cursor style to default before executing a command, then set the custom style again when the command exits. This way applications like vim, bash, python and any other interactive CLI application would not be affected by it.

(Put a different way, temporarily set `ZVM_CURSOR_STYLE_ENABLED=false` while a process is running in the terminal)

**Comment by jeffreytse** [comment]
Hi @Hubro 

Thanks for the reporting about some applications don't handle switching cursor styles, I will pay attention to enhance this cursor behavior for better experience.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @Hubro 

🎉 This issue has been settle down and now it supports to auto restore cursor to user defualt when an interactive program (e.g. vim, bash, etc) starts. Please update your plugin to the latest version for the enhancement.

Thanks and regards

**Comment by Hubro** [comment]
It works! Thanks for the quick fix :)
