### ISSUE TITLE
zsh-vi-mode overrides word separator

### ISSUE THREAD

**Issue by Hubro** [jeffreytse/zsh-vi-mode#37]
By default (if I disable this plugin) zsh will treat each directory in the path `/home/hubro/Dropbox/Config` as separate words, so when I press Ctrl+w repeatedly, it will first delete "Config", then the "/", then "Dropbox" and so on.

When using zsh-vi-mode, pressing Ctrl+w will remove the entire path, treating it as one long word.

To test, type "cd foo/bar/baz" into the terminal and press Ctrl+w. Then, run zsh without plugins (`zsh -f`) and repeat the test.

I think zsh-vi-mode should keep the default, or at least provide a way to configure word separators. If this is already possible, it should be documented in the README.

**Comment by jeffreytse** [comment]
Hi @Hubro 

Thanks for the reporting and this issue has been addressed and fixed. Please update your plugin to the latest version.

Thanks and regards

**Comment by Hubro** [comment]
@jeffreytse What has been done? 😄 I don't see anything new in the README and I don't see any new behavior:


https://user-images.githubusercontent.com/597206/109783893-c154a800-7c0a-11eb-941f-08980fd97e1d.mov

**Comment by jeffreytse** [comment]
Hi @Hubro, I have fixed the issue about the `ctrl-w` behavior in the insert modee, the behavior follows the emacs `ctrl-w`.

**Comment by Hubro** [comment]
@jeffreytse Is there any way to get this behaviour in zsh-vi-mode?

https://user-images.githubusercontent.com/597206/109804237-51eab280-7c22-11eb-9a4e-d1a220d37c4e.mov

In other words, when writing a long path, I want to be able to erase backwards one word at a time using Ctrl+w, rather than deleting the whole path. I don't want the forward slash character to be considered a "word character".

**Comment by Hubro** [comment]
It seems like the old behaviour (backward-kill-word) works as expected if I set `WORDCHARS` myself. I didn't know about this variable when I opened this issue, and it solves my issue.

I would probably revert the default binding of ^W to backward-kill-word, as that's what most Vi users will expect.

**Comment by jeffreytse** [comment]
Hi @Hubro 

I have reverted the default binding of `^W` to `backward-kill-word`, as that's what most Vi users will expect.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @Hubro 

Could this issue be closed now? :)

Thanks and regards

**Comment by Hubro** [comment]
Yes, for sure!

**Comment by noahgitsham** [comment]
@jeffreytse I currently have this issue. It occurs with both my regular config and a completely blank config (aside from sourcing zvm).
