### ISSUE TITLE
[BUG] Cannot exit normal mode with `a` or `i`

### ISSUE THREAD

**Issue by ztlevi** [jeffreytse/zsh-vi-mode#38]
## Problem description

I realized exit normal mode in zsh-vi-mode breaks recently. I cannot use a or i to enter insertion mode again. Are you aware anything like that?

I observed this behavior works at commit d7d6fba but breaks at df675da.

my zsh version: zsh 5.8 (x86_64-apple-darwin19.6.0)

## Reproduce with my current environment setup with the following steps.
1.  Clone

```sh
bash <(curl -s https://raw.githubusercontent.com/ztlevi/Dotfiles/master/bootstrap.sh)
cd ~/Dotfiles
export ZDOTDIR=$HOME/Dotfiles/shell/zsh
```

2.  Comment out
    [these lines](https://github.com/ztlevi/Dotfiles/blob/master/shell/zsh/.zshrc#L5-L11) in my zsh
    config.

3.  Add `antigen bundle jeffreytse/zsh-vi-mode` in `$HOME/Dotfiles/shell/zsh/bundles.zsh`

4.  `./deploy shell/zsh` then start a new zsh in the current terminal

**Comment by jeffreytse** [comment]
Hi @ztlevi 

The issues (#39, #40) have addressed and fixed some bugs that caused the mode stuck, you can update your plugin to the latest version and test again.

Thanks and regards

**Comment by ztlevi** [comment]
Thanks! I'm on 41bb661 commit now but it's still not working. I also realized I can exit with `s` key but that will delete the content before the cursor.

**Comment by ztlevi** [comment]
You can update the plugins by using `antigen update`

**Comment by ztlevi** [comment]
@jeffreytse Did you happen to resolve this bug? Let me know if you need more help...

**Comment by jeffreytse** [comment]
Hi @ztlevi

Could you update to the latest version and tell me if this issue still appears? I will focus on it and fix it as soon as possible.

Thanks

**Comment by ztlevi** [comment]
Thanks! It actually works like a charm!
