### ISSUE TITLE
incompatible with fzf

### ISSUE THREAD

**Issue by worldpotato** [jeffreytse/zsh-vi-mode#4]
First of all, let me say that it is a really nice plugin! Thank you!

But I found out that it is not compatible with some fzf features like the backward search. Which is really a bummer for me.

If I should provide some more infos like log files, my configuration etc. please let me know. I don't really know what could help you.

**Comment by jeffreytse** [comment]
Hi @worldpotato 

Firstly, so happy to heard that you love this plugin, this is my pleasure. Currently it's a really new plugin and I'm so sorry for that you met a compatible issue. And I will work to solve this problem, please be patient.

I will let you know if I need any more detail information about this issue. And welcome to star this project for updates and further features in the future.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @worldpotato

Thanks for your patient. Since this plugin will overwrite the previous key bindings, this causes the `fzf` key bindings to fail. Currently this plugin has provided a mechanism to execute extra commands ( bb1857d ).

Now you have the below aspects for executing something:

```zsh
zvm_before_init_commands=()
zvm_after_init_commands=()
zvm_before_select_vi_mode_commands=()
zvm_after_select_vi_mode_commands=()
```

You can solve the compatibility issue as below:

```zsh
zvm_after_init_commands+=('[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh')
```
or
```zsh
function my_init() {
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
}
zvm_after_init_commands+=(my_init)
```
or 

```zsh
# the plugin will auto execute this function
function zvm_after_init() {
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
}
```

Thanks and regards

**Comment by worldpotato** [comment]
Wow!
Thank you very much for the patch!

Also a lot of thanks for the detailed explenation how to use it. Will try that later!

**Comment by BerkeleyTrue** [comment]
Works for me as well! Thanks for the quick response!

**Comment by jeffreytse** [comment]
Hi @worldpotato @BerkeleyTrue 

:tada: Firstly, I hope your guys have a day. And now I have a big good news for you.

The latest commit ( aad07d8 ) now has supported **the lazy keybindings feature**, this feature will postpone some keybindings (i.e. normal/visual mode) to the first time you enter the normal mode. This feature can greatly improve the start up speed, it is faster almost 800% - 1000% than the last version. Hope you guys will like it.

Thanks and regards.

**Comment by BerkeleyTrue** [comment]
@worldpotato I think this issue can be closed

**Comment by worldpotato** [comment]
@BerkeleyTrue Absolutly
