### ISSUE TITLE
problems in vim built-in terminal when vim is opened in tmux

### ISSUE THREAD

**Issue by ZhiyuanLck** [jeffreytse/zsh-vi-mode#41]
When I use the plugin in vim built-in termimal in **tmux**, every character I typed was followed by an extra "6 ", and there is an extra "q" at end.

To produce:
1. create and enter a new tmux session by `tmux`
2. open vim by `vim -u NONE`
3. open terminal by `:term`
4. enter zsh shell by `zsh`
5. type any character

**Comment by jeffreytse** [comment]
Hi @ZhiyuanLck 

Thanks for the reporting. I will pay attention to this issue and welcome to star this project for further update in the future.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @ZhiyuanLck 

Thanks for the reporting and this issue has been addressed and fixed. Please update your plugin to the latest version.

Thanks and regards

**Comment by ZhiyuanLck** [comment]
Cool!
