### ISSUE TITLE
When ZVM_VI_ESCAPE_BINDKEY=jj then typing j<space> gives you j\s

### ISSUE THREAD

**Issue by pdbradley** [jeffreytse/zsh-vi-mode#43]
jj is my goto in vim for escape mode so I was delighted to see I can put the same trigger in this plugin.

However, now if I'm in insert mode and type "j "  (j followed by a spacebar) it immediately inserts "j\s"

Which is hard because I basically navigate around folders with the jump command.

recording:  [https://share.getcloudapp.com/Jru1EERQ](https://share.getcloudapp.com/Jru1EERQ)

**Comment by jeffreytse** [comment]
Hi @pdbradley 

Thanks for the reporting, I will pay attention to this issue and fix it as soon as possible.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @pdbradley 

This issue has been addressed and fixed. Please update your plugin to the latest  version.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @pdbradley , is this issue still unresolved? Welcome to get back me if you have any question. : )
