### ISSUE TITLE
VV to edit in $EDITOR get permission denied on MacOS.

### ISSUE THREAD

**Issue by lkhphuc** [jeffreytse/zsh-vi-mode#44]
The `vv` command in Normal mode create a tmp file in `/tmp/`, which normal user does not have in Macos. Could the directory for temporary file be changed to something else, such as `/var/tmp/` similar to neovim?

**Comment by jeffreytse** [comment]
Hi @lkhphuc 

Thanks for the reporting, I will pay attention to this issue and fix it as soon as possible.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @lkhphuc 

This issue has been addressed and fixed. Please update your plugin to the latest version.

Thanks and regards

**Comment by lkhphuc** [comment]
Thank you.
