### ISSUE TITLE
[Bug] Conflict with oh my zsh sudo plugin

### ISSUE THREAD

**Issue by androidfans** [jeffreytse/zsh-vi-mode#46]
zinit snippet OMZ::plugins/sudo/sudo.plugin.zsh

sudo plugin makes you can just double click esc to auto add a sudo to the start of a line.

But this plugin works well with zsh's default vi mode

**Comment by jeffreytse** [comment]
Hi @androidfans 

Thanks for the reporting and patience, this issue has been settled down on this commit b9232fb, please update your plugin to the latest version.

Thanks and regards

**Comment by androidfans** [comment]
will not repro
