### ISSUE TITLE
Plugin override (Shift-)Tab by default?

### ISSUE THREAD

**Issue by lkhphuc** [jeffreytse/zsh-vi-mode#47]
Hi, 
I was having some trouble using this plugin with other plugin that use Shift-Tab (and Tab) for auto completion, such as https://github.com/marlonrichert/zsh-autocomplete 
These plugins work fine if I disable this plugin, but I don't see any mention (nor reason) for Vim plugin to use the Tab or Shift-TAb function. Is this a bug or a feature that I miss?

**Comment by jeffreytse** [comment]
Hi @lkhphuc 

Thanks for your reporting and patience, about the key override issue, you can read [here](https://github.com/jeffreytse/zsh-vi-mode#execute-extra-commands). Also, for the `fzf` keybinging issue you can refer to #24.

Thanks and regards

**Comment by lkhphuc** [comment]
Thank you. That fixed my issue.
