### ISSUE TITLE
ZVM_VI_ESCAPE_BINDKEY not adding pressed key after timeout

### ISSUE THREAD

**Issue by krzykli** [jeffreytse/zsh-vi-mode#49]
Hello,

Firstly, thanks for the amazing plug-in!
I've just pulled the latest version and I'm running into an issue with my escape bindkey ("jk").

Currently in insert mode if I press "j" nothing happens, no matter how long I wait.
The expected behaviour though should be that "j" appears in the console after the time specified by VIM_KEYTIMEOUT passes, just like in vim.

Cheers,
kk

**Comment by jeffreytse** [comment]
Hi @krzykli 

Thanks for the reporting, I will focus on this issue as soon as possible, welcome to star this project for further updates in the future.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @krzykli 

Could you update your plugin to the latest version and check again if this issue is still existed?

Thanks and regards

**Comment by krzykli** [comment]
Hey @jeffreytse,

Actually after pulling master my escape sequence doesn't work at all :( 
Maybe there's something wrong on my side? Can you exit insert mode with "jk" locally?

Cheers,
kk

**Comment by jeffreytse** [comment]
Hi @krzykli 

Yes, I can exit insert mode with `jk` locally. Could you provide me some details? I really want to help to settle down your issue.

Cheers

**Comment by krzykli** [comment]
Ah actually, when I spawn a nested zsh it works like a charm!
It must be something in my config, so don't worry about it. From what I can see the bug is fixed.
Thanks again!

**Comment by jeffreytse** [comment]
Hi @krzykli , Could we close this issue now? : )

**Comment by krzykli** [comment]
Ops, absolutely! :)

**Comment by jeffreytse** [comment]
Hi @krzykli ,

Thank you for getting back and telling me that you have settled down this issue. And welcome to star this project for further updates in the future. : )

Thanks and regards.
