### ISSUE TITLE
[Bug]W E B upper case object doesn't work on mac os big sur

### ISSUE THREAD

**Issue by androidfans** [jeffreytse/zsh-vi-mode#58]
As you can see , it just delete one character
![Mar-16-2021 19-46-18](https://user-images.githubusercontent.com/6452650/111304322-90f01d80-8690-11eb-948b-30662891ff29.gif)

**Comment by jeffreytse** [comment]
Hi @androidfans 

Thanks for the reporting, I will pay attention to this issue and fix it as soon as possible.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @androidfans 

This issue has been addressed and fixed. Please update your plugin to the latest version.

Thanks and regards

**Comment by androidfans** [comment]
wow, so quick.  I will try it when i get home @jeffreytse

**Comment by androidfans** [comment]
It works!  thx a lot
