### ISSUE TITLE
Bug: Adding zsh-vi-mode causes nav keys (Home, End, PgUp and PgDn ) to break

### ISSUE THREAD

**Issue by deafmute1** [jeffreytse/zsh-vi-mode#59]
Hi, this issue occurred today after updating all my plugins. I narrowed it down to zsh-vi-mode by turning plugins on/off until reproducing. 

Basically: Home, End, PgUp and PgDn emit the incorrect scan codes according to both `terminfo` and `showkey --scancode` after sourcing zsh-vi-mode . Also, multiple keys have the same code - Home and End are both `[`, while PgUp and PgDn are both `[~` .

**Comment by jeffreytse** [comment]
Hi @deafmute1 

Thank you for reporting this issue. I will focus on this issue and fix it and welcome to star this project for further updates in the future.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @deafmute1 

Thanks for the patience, this issue has been addressed and fixed, please upadte your plugin to the latest version. And welcome to star this project for further updates in the future. : )

Thanks and regards.

**Comment by jeffreytse** [comment]
Hi @deafmute1

Could we close this issue? If you still have other issues, please let me known. : )

Thanks and regards

**Comment by fdietze** [comment]
Hi, `Home` and `End` keys are not working for me. Neither in insert, nor in normal mode. Any ideas how to debug?

**Comment by jeffreytse** [comment]
Hi @fdietze 

Could you give me some more instructions on your issue? Such as your `.zshrc`, what plugin was corrupted and so on.

Thanks and regards

**Comment by fdietze** [comment]
I just stripped my `.zshrc` down to:

```zsh
source "${HOME}/.zgen/zgen.zsh"
if ! zgen saved; then
    echo "creating zgen save..."

    zgen load jeffreytse/zsh-vi-mode

    zgen save
fi
```

**Comment by jeffreytse** [comment]
@fdietze For this, what plugin keybindings on the `Home` and `End` do not work? In other words, what hehavior do you expect?

**Comment by fdietze** [comment]
I expected `Home` to do the same as `0` in normal and insert mode and `End` the same as `$`. Do I have to map them manually?

Thank you

**Comment by Davincible** [comment]
I'm having the same issue. By default, Manjaro registers the keys as below, which works fine except when I source this plugin. Do I need to set a separate keybinding for this plugin? if so which

```
## Keybindings section
bindkey -e
bindkey '^[[7~' beginning-of-line                               # Home key
bindkey '^[[H' beginning-of-line                                # Home key
if [[ "${terminfo[khome]}" != "" ]]; then
  bindkey "${terminfo[khome]}" beginning-of-line                # [Home] - Go to beginning of line
fi
bindkey '^[[8~' end-of-line                                     # End key
bindkey '^[[F' end-of-line                                     # End key
if [[ "${terminfo[kend]}" != "" ]]; then
  bindkey "${terminfo[kend]}" end-of-line                       # [End] - Go to end of line
fi

```

**Comment by jeffreytse** [comment]
Hi @Davincible @fdietze 

Thanks for the information, I will try to dig up this issue and fix it as soon as possible.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @fdietze 

For the default vi keybindings (i.e. `bindkey -v`) without this plugin, the behaviors of `Home` and `End` aren't going to the beginning/end of line. Are them bound by yourself or aother plugin?

Thanks and regards

**Comment by fdietze** [comment]
@jeffreytse 

That's correct, the default zsh vi mode does not map Home/End. But the bash vi mode and vim support it by default.

I thought that it would make sense to map these keys by default. Something like:

```
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey -M visual "^[[H" beginning-of-line
bindkey -M visual "^[[F" end-of-line
bindkey -M vicmd "^[[H" beginning-of-line
bindkey -M vicmd "^[[F" end-of-line
```

What do you think?

**Comment by Davincible** [comment]
Can confirm, also managed to do it like that, my key codes were just different with

**Comment by jeffreytse** [comment]
Hi @fdietze @Davincible 

So sorry for the late following up, I have been busy recently, thanks for your suggestions. I will take a consideration for adding them to default keybindings. Before that you can easily fullfil these keybindings by adding manually with `zvm_after_init` function, here is the related [document](https://github.com/jeffreytse/zsh-vi-mode#execute-extra-commands) for you guys. Have a good day! : ) 

Thanks and regards
