### ISSUE TITLE
Cursor in insert mode is forced to be vertical line.

### ISSUE THREAD

**Issue by ftpd** [jeffreytse/zsh-vi-mode#6]
I always had box cursor and I don't like to have it another way. Since using this plugin, it forces my cursor to be vertical line instead of box (box is in normal mode only - exactly opposite that I want it to be).

Any chance to add an option to set it?

**Comment by jeffreytse** [comment]
Hi @ftpd 

In fact, this plugin has provided an option for configurating the cursor style. And you can find out all the configuration details in the head of source code:

https://github.com/jeffreytse/zsh-vi-mode/blob/aad07d8bc4197d6a1e4458fe29fb31cb451f7dad/zsh-vi-mode.zsh#L25-L29
and
https://github.com/jeffreytse/zsh-vi-mode/blob/aad07d8bc4197d6a1e4458fe29fb31cb451f7dad/zsh-vi-mode.zsh#L119-L125

As mention above, you can set the cursor style in insert mode to a beam as below in your `.zshrc` file:

```zsh
# Set the sursor stlye of defferent vi modes
if [[ ${TERM:0:5} == 'xterm' ]]; then
  ZVM_VI_INSERT_MODE_CURSOR=$ZVM_CURSOR_XTERM_BLOCK
else
  ZVM_VI_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLOCK
fi
```

Thanks and regards

**Comment by ftpd** [comment]
Thanks - I haven't seen it in Readme, so I somehow thought it's not supported. I should take a look into code ;-)

I'm closing this issue as fixed now.

**Comment by jeffreytse** [comment]
Hi @ftpd 

😄 You are welcome. And you can star this repository for the updates and features in the future. Currently I'm focusing on this plugin and making it better and better.

Thanks and regards.

**Comment by jeffreytse** [comment]
Hi @ftpd 

The latest commit ( f9b508d ) has provided some options for users to custom the cursor style for better terminal compatibility.

1. You can set your cursor style for different vi mode:

```zsh
# ZVM_NORMAL_MODE_CURSOR:
# the prompt cursor in normal mode
#
# ZVM_INSERT_MODE_CURSOR:
# the prompt cursor in insert mode
#
# ZVM_VISUAL_MODE_CURSOR:
# the prompt cursor in visual mode
#
# ZVM_VISUAL_LINE_MODE_CURSOR:
# the prompt cursor in visual line mode
```

2. And the below cursor style are supported:

```zsh
ZVM_CURSOR_BLOCK
ZVM_CURSOR_UNDERLINE
ZVM_CURSOR_BEAM
ZVM_CURSOR_BLINKING_BLOCK
ZVM_CURSOR_BLINKING_UNDERLINE
ZVM_CURSOR_BLINKING_BEAM
```

3. Custom your cursor style is easy as below:

```zsh
ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLOCK
ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_BLINKING_UNDERLINE
```

Thanks and regards

**Comment by ftpd** [comment]
Wow, neat! Thanks!
