### ISSUE TITLE
Configuration of ZVM_LINE_INIT_MODE must follow 'source $ZSH/oh-my-zsh.sh'

### ISSUE THREAD

**Issue by aserowy** [jeffreytse/zsh-vi-mode#64]
Hi,

i've found zsh-vi-mode after being disappointed with the std vi mode of ohmyzsh. My shell is running on debian (wsl2). I tried setting

```zsh
ZVM_LINE_INIT_MODE=$ZVM_MODE_NORMAL
```

in my .zshrc before sourcing (other configurations work e.g. jk to leave modes). After restarting i am getting the same behaviour like before (default mode).

Am i missing something? What can i contribute to analyse this?

Kind regards
Alexander

**Comment by jeffreytse** [comment]
Hi @aserowy 

Could you provide your `.zshrc` content to dig further information for me?

Thanks and regards

**Comment by aserowy** [comment]
Heho,

of course!

```zsh
# instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# zsh
export ZSH="/home/serowy/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

# ohmyzsh
plugins=(
  debian
  docker
  docker-compose
  git
  ssh-agent
  zsh-vi-mode
)

ZVM_LINE_INIT_MODE=$ZVM_MODE_NORMAL
ZVM_VI_ESCAPE_BINDKEY=jk

zstyle :omz:plugins:ssh-agent identities [ keys ]

source $ZSH/oh-my-zsh.sh

# user configuration
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

Kind regards and thx in advance
Alexander

**Comment by jeffreytse** [comment]
Hi @aserowy 

All the options should be put after you sourcing the `oh-my-zsh`, it is totally because of all the omz plugins being sourced at the stage that you source `oh-my-zsh`. That should be the below snippet:

```zsh
...

# ohmyzsh
plugins=(
  zsh-vi-mode
)

source $ZSH/oh-my-zsh.sh

# Set the line initial mode
ZVM_LINE_INIT_MODE=$ZVM_MODE_NORMAL

# Set the escape key only for insert mode
ZVM_VI_INSERT_ESCAPE_BINDKEY=jk

...
```

Thanks and regards

**Comment by aserowy** [comment]
Thank you! It worked! :)

I will put a pr today to add to the documentation at ohmyzsh. (If that is ok)

Kind regards
Alexander

**Comment by jeffreytse** [comment]
Hi @aserowy 

You're welcome! Hope you have a good day. : )

Thanks and regards

**Comment by aserowy** [comment]
Yip, having a good one. You made it even better! <3
