### ISSUE TITLE
Unexpected behavior of `ciw` or `caw`

### ISSUE THREAD

**Issue by CloseToZero** [jeffreytse/zsh-vi-mode#67]
# Reproduce

* Open a new terminal.
* Input the content "test1 test".
* Put the cursor at second "e" like "test1 t_e_st".
* Press `ciw` (or `caw` etc).

# Result
Only "est" is deleted.

# Expected behavior
The "test" should be deleted.

**Comment by jeffreytse** [comment]
Hi @CloseToZero 

Thanks for the reporting, in fact I have found this issue today, and I will try to settle it down as soon as possible.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @CloseToZero 

Thanks for the patience, this issue has been addressed and fixed. Please update your plugin to the latest version.

Thanks and regards

**Comment by CloseToZero** [comment]
@jeffreytse
Thank you for your quick response.
The bug is almost fixed but still has a minor problem:
* Input the content "test".
* Place the cursor at the final character like "tes_t_".
* Press `ciw`.
Result: the content remains unchanged.
This behavior is inconsistent with `ce` and `cw`:
* Input the content "test".
* Place the cursor at the final character like "tes_t_".
* Press `ce`.
Result: the final "t" is deleted.

**Comment by jeffreytse** [comment]
Hi @CloseToZero

Thanks for the reporting, this issue has been addressed and fixed. Please update your plugin to the latest version.

Thanks and regards
