### ISSUE TITLE
Installation Blocks FZF ^R Behavior

### ISSUE THREAD

**Issue by nsapse** [jeffreytse/zsh-vi-mode#68]
FZF replaces ^R with the ability to fuzzy-find previous commands. zsh-vi breaks this replacing it with the default behavior.

**Comment by jeffreytse** [comment]
Hi @nsapse 

Thanks for the reporting and patience, about the key override issue, you can read [here](https://github.com/jeffreytse/zsh-vi-mode#execute-extra-commands). Also, for the `fzf` keybinging issue you can refer to #24.

Thanks and regards

**Comment by nsapse** [comment]
I see you marked this good first issue. Are you looking for contributors?

**Comment by jeffreytse** [comment]
I use this label for the new  user to better find some issues like this and quickly get relevant references. : )
