### ISSUE TITLE
This plugin prevents abbreviations from expanding

### ISSUE THREAD

**Issue by medwatt** [jeffreytse/zsh-vi-mode#69]
I am using [this](https://github.com/olets/zsh-abbr) plugin to expand abbreviations. 

For example:

```shell
abbr dl="cd ~/Downloads"
```

Typing `dl` followed by `<space>` expands `dl` into `cd ~/Downloads`. This works fine with the default vi-mode plugin from oh-my-zsh. However, when this plugin is enabled, abbreviations fail to expand.

**Comment by jeffreytse** [comment]
Hi @medwatt 

Thanks for the reporting. I will focus on this issue and try to settle it as soon as possible. Welcome to star this project for the further updates in the future.

Thanks and regards
