### ISSUE TITLE
[BUG] output disapears

### ISSUE THREAD

**Issue by ztlevi** [jeffreytse/zsh-vi-mode#7]
Hi,

Thanks for this great plugins. I found this plugin very useful, but I realized the output will disappear. And I have no idea why this would happen.

For the reference. I am using my [Dotfiles](https://github.com/ztlevi/Dotfiles/blob/master/shell/zsh/.zshrc). During testing, I comment out [these lines](https://github.com/ztlevi/Dotfiles/blob/master/shell/zsh/.zshrc#L3-L14) and leave only antigen specific config for testing. 

I also tried another theme, but it still happens. The screenshots are taken and it happens in a second.

<img width="2048" alt="Screen Shot 2021-01-27 at 3 17 48 AM" src="https://user-images.githubusercontent.com/16655096/105893869-9779f580-604e-11eb-95eb-e842f98c5cd0.png">
<img width="2048" alt="Screen Shot 2021-01-27 at 3 17 58 AM" src="https://user-images.githubusercontent.com/16655096/105893882-9c3ea980-604e-11eb-8493-0bae9ad878bc.png">

**Comment by ztlevi** [comment]
Are u able to reproduce that? I can add more instructions if u cannot

**Comment by jeffreytse** [comment]
Hi @ztlevi 

Yes, I was not able to reproduce this issue, I need more instructions from your side.

Thanks and regards

**Comment by ztlevi** [comment]
Can u try the following?

1. Clone
```
bash <(curl -s https://raw.githubusercontent.com/ztlevi/Dotfiles/master/bootstrap.sh)
cd ~/Dotfiles
export ZDOTDIR=$HOME/Dotfiles/shell/zsh
```

2. Comment out [these lines](https://github.com/ztlevi/Dotfiles/blob/master/shell/zsh/.zshrc#L3-L14) in my zsh config.

3. Add `antigen bundle jeffreytse/zsh-vi-mode` in `$HOME/Dotfiles/shell/zsh/bundles.zsh`
4. `./deploy shell/zsh` then start a new zsh in the current terminal
5. Try `ls`

**Comment by jeffreytse** [comment]
Hi @ztlevi 

Currently I am digging this this issue, please be patient, I will update here if got any progress.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @ztlevi 

🎉 Thanks for your instructions and this issue has been addressed and settled down, please update the plugin and try it again.

Thanks and regards

**Comment by ztlevi** [comment]
@jeffreytse Thanks! It works! 

Antigen is little weird, I'm using `antigen update` but it only updates some other plugins. I have to delete or manually upgrade zsh-vi-mode.

**Comment by jeffreytse** [comment]
Hi @ztlevi 

You are welcome! Hope this plugin can make your work more convenient. 👍 And currently I'm using the `zinit` for plugin management, maybe you can have a try.

Thanks and regards
