### ISSUE TITLE
(help) unable to paste on the same line.

### ISSUE THREAD

**Issue by 5c0tt-b0t** [jeffreytse/zsh-vi-mode#71]
Hi, I wrote 'help' as it may just be me, but I am unable to paste on the same line with this plugin installed, 'p' pastes on a newline under the current line, 'P' pastes on the current line but pushes whatever is on my current line to a newline below, how do I paste like on the same line like I do with normal 'bindkey -v' keys?
Thankyou.

**Comment by jeffreytse** [comment]
Hi @5c0tt-b0t 

Could you provide me some instructions to reproduce this issue?

Thanks and regards

**Comment by 5c0tt-b0t** [comment]
Of course, I am using an Android tablet with Termux (and `termux-api`), I use `zplug` to manage plugins, I only use a few plugins, and I source yours last to try ensure no binds are overwritten.
To reproduce, at the command line try:
```bash
$ test123<ESC>/<dd>/<p>

$ test123
    test123 <-- it pasted here, on a new line.
```
Or:
```bash
$ test123<ESC>/<dd>/<P>

$ test123 <-- it pasted here, on a new line.
    test123
```
If it helps, this has never happened with 'bindkey -v' and oh-my-zsh's vi-mode plugin.
By the way, I looked through the script and the extent you have gone to... it looks amazing! Im not new to shell but I am new to zsh and it was bash's readline with its limited vi-mode that ended up making me switch after all these years, there are a few good vi-mode plugins for zsh, but after trying/scanning the scripts, yours is by far the most advanced, great job!

**Comment by jeffreytse** [comment]
Hi @5c0tt-b0t 

Firstly, thanks for your support. You use `dd` to delete a line, and then use `p` or `P` to paste it, right?

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @5c0tt-b0t 

If you use `dd` command, then the behavior is `p` for pasting after below line and `P` is for pasting above line, you can try the same behaviors in the VIM edior or NVIM editor.

Thanks and regards

**Comment by 5c0tt-b0t** [comment]
I apologise for the delayed response!
I do understand that vi/vim/nvim will do this and that your aim is a truly vi-like experience, what I mean is that is is a regression in usability, there is a reason why bash/zsh etc didnt include this feature, as it does not give us any benefit, the shell works on one line, so by default it appends/prepends on the same line, this way we can hit enter and our command runs, currently that is not the case here, including vi's behaviour is a regression that gives us less usability.
It would be great if either:
* it was reverted back to normal vi-mode behaviour, or better yet:
* if you could do this, your a wizard! (and I would be very grateful!)
to allow your feature to work, when pasting, append the current line with ` \` (space-backslash) then our commands will continue to run perfectly but also your feature would no longer be a regression, instead a progression in usability, your truly vim-like approach would then add something more to the our shell, rather than take away.

Thank you again, its really appreciated!

**Comment by jeffreytse** [comment]
Hi @5c0tt-b0t 

I understand your concern, but there will be another group of people who will ask why when I use `dd` or `yy` to delete or copy not as a line.

For example, some people may edit a multi-line command similar to `curl` and split it into multiple lines with slash

```zsh
$ curl -H "Accept-Charset: utf-8" \
       -H "Content-Type: application/x-www-form-urlencoded" \
       -H "Connection: keep-alive" \ 
       http://example.com
```

They would use `dd` to delete a line, then they can use `P` to paste to above line (for swapping lines), or they would want to use  `yy` to yank a head and `p` to below line and then change the content easily.

Is it really difficult to you use `^y$` copy a line without newline character for this case? I will be happy to do a further discuss with you.

Thanks and regards

**Comment by 5c0tt-b0t** [comment]
Once again, sorry for the delay, been so busy!
You know what, you are right, whilst I still believe its not as quick/easy (lazy!) as standard zsh behaviour, I imagined myself using a more complex version of your example (multiline, between a do/done case/esac if/then) and I too believe vim behaviour is very welcome! allow me to close this with a huge thanks for both your hard work (its great!) and your pleasant replies.

**Comment by jeffreytse** [comment]
Hi @5c0tt-b0t 

Thanks for your good issue and maybe I will add an option for setting this `yy` or `dd` behavior not as a line in the future if there are many users ask for this.

Thanks and regards
