### ISSUE TITLE
How to disable '<' prompt in normal mode

### ISSUE THREAD

**Issue by MohamedIrfanAM** [jeffreytse/zsh-vi-mode#75]
I want to disable '<' in normal, it messes up my prompt (starship). Please help...
BTW your plugin is so useful that I can't live without it.

**Comment by jeffreytse** [comment]
Hi @MohamedIrfanAM 

Firstly, thanks for the support! As you said you are using the starship, so the vi mode status prompt is provided by starship, you can config the vi mode prompt by starship configuration file (`~/.config/starship.toml`) from its [document](https://starship.rs/config/#character).

And welcome to star this project for further updates in the future. 👍 

Thanks and regars

**Comment by MohamedIrfanAM** [comment]
Thank you so much, fixed it :)

**Comment by MohamedIrfanAM** [comment]
one more question, i have mapped jk to esc(normal mode) using ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
but when i type 'k' i noticed a lag. can i fix this too

**Comment by jeffreytse** [comment]
Hi @MohamedIrfanAM 

Is it typing `j` a little bit lag, not typing `k`?

Thanks and regards

**Comment by MohamedIrfanAM** [comment]
while typing k
