### ISSUE TITLE
Surround not working

### ISSUE THREAD

**Issue by mskar** [jeffreytse/zsh-vi-mode#8]
I cloned and sourced the plugin:
```sh
git clone https://github.com/jeffreytse/zsh-vi-mode.git $HOME/.zsh-vi-mode
source $HOME/.zsh-vi-mode/zsh-vi-mode.plugin.zsh
```
Incrementation/decrementation works (`<C-a>`/`<C-x>`), but surround (e.g. `yse"`) doesn't.
I tried it with visual selection and with motions. Am I doing something wrong?

**Comment by mskar** [comment]
Ok, `S"` works to surround with " in visual mode, but `ds` cs` and `ys` don't work for me.
It may be something in [my config](https://github.com/mskar/setup/blob/84cc2baac73a4d035ca24238b45953e6503a624a/.zshrc) is conflicting with the plugin.

**Comment by jeffreytse** [comment]
Hi @mskar 

I think you can utilize the method of exclusion (i.e. comment some lines) to check which part caused the confliction. Any issue welcome to commit here, I will try to help you figure it out.

Thanks and regards

**Comment by mskar** [comment]
Thanks, I will experiment with commenting out lines and then report back here.

**Comment by mskar** [comment]
I tried this other plugin: https://github.com/softmoth/zsh-vim-mode
and the surround functionality doesn't really work for me there either, so it's definitely a problem with my config😄

**Comment by kyazdani42** [comment]
Hi, i don't think it's a problem with your config. I've noticed `cs"` doesn't work even if only zsh_vi_mode is enabled.
you can reproduce easily with `a="some string"` and trying to `cs"'` inside the string doesn't work. Not sure why this is happening, it works fine when replacing `'`.
Although for brackets, it does work partially: with `a=(echo 1)`, you got to slowly do the `cs)]` command to get it working, if you do it too fast, it will delete a character.

**Comment by jeffreytse** [comment]
Hi @kyazdani42 

Thanks for your details, I have reproduced the issue and I will fix this problem as soon as possible.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @kyazdani42 @mskar 

Thanks for your details on the surround issue. And now this issue about changing surround by `cs"` or `S"` has been fixed. Welcome to update your plugin to the latest version.

Thanks and regards

**Comment by roosta** [comment]
Hi all, I was about to post a comment about this not working for me even after the patch, but I got it working properly by removing this environment variable: `KEYTIMEOUT`. I had it set to `1`, which resulted in change surround not working properly. Hope this can be helpful in some way.

**Comment by eyev0** [comment]
> Hi all, I was about to post a comment about this not working for me even after the patch, but I got it working properly by removing this environment variable: `KEYTIMEOUT`. I had it set to `1`, which resulted in change surround not working properly. Hope this can be helpful in some way.

thank you!
