### ISSUE TITLE
`Y` is not yanking as a line

### ISSUE THREAD

**Issue by jeffreytse** [jeffreytse/zsh-vi-mode#81]
# Reproduce
- Open a new terminal.
- Input the content "abc".
- Press `Y` and then `p`.

# Result
The content becomes:
```zsh
abcabc
```

# Expected behavior
The yanking content should be paste as a new line:
```zsh
abc
abc
```

**Comment by stutterrrrer** [comment]
Hi, can I tag on this and ask about copying to system clipboard? is there a way to do that in normal mode?

**Comment by jeffreytse** [comment]
> system

Hi @stutterrrrer , please refer to issue #19.
