### ISSUE TITLE
Entering insert mode with A and auto-suggestion places cursor at next to final character

### ISSUE THREAD

**Issue by gotgenes** [jeffreytse/zsh-vi-mode#83]
When an auto-suggestion is present, and the user is in normal mode, entering insert mode with `A`, the cursor will be placed before the final character.

![autosuggest](https://user-images.githubusercontent.com/8517/113364938-a3618c80-9309-11eb-8df6-77abbccb4389.gif)

Sequence of events, above:

1. From insert mode, type `echo`
2. zsh auto-suggestion suggests completion with previous command of `echo $PATH`, cursor remains after the `o` in `echo`.
3. Hit <kbd>Esc</kbd> to enter normal mode
4. Type <kbd>Shift</kbd>+<kbd>A</kbd> to enter insert mode. Cursor is before the `H` of `$PATH`; the expected behavior is the cursor is placed immediately after the `H`.
5. Hit <kbd>Esc</kbd> to re-enter normal mode, making the cursor position more clear.

The expected behavior is that the cursor would be placed after the final character.

**Comment by jeffreytse** [comment]
Hi @gotgenes

This behavior is a feature of default [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) (related [code](https://github.com/zsh-users/zsh-autosuggestions/blob/ae315ded4dba10685dbbafbfa2ff3c1aefeb490d/zsh-autosuggestions.zsh#L71-L77)) for easier choosing the auto suggestion. You can config the option `ZSH_AUTOSUGGEST_ACCEPT_WIDGETS` to change the behavior:

```zsh
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
  forward-char
  end-of-line
  vi-forward-char
  vi-end-of-line
  vi-add-eol
)
```

This widget `vi-end-of-line` is added to by default, you can remove it to settle your issue. Or just move your cursor backward a character (i.e. cursor at `h`), then press `A`.

Thanks and regards

**Comment by gotgenes** [comment]
Interesting! zsh-vim-mode's behavior is to place the cursor at the end of line (after the auto-suggested text) so I had gotten used to that behavior.

**Comment by jeffreytse** [comment]
Yes, it's better to keep compatibility with the `zsh-autosuggestions` plugin, and this issue is introduced by `zsh-autosuggestions`, so you just need to do the simple configuration with `ZSH_AUTOSUGGEST_ACCEPT_WIDGETS` option, it will be settled down perfectly! : )

**Comment by gotgenes** [comment]
Thanks for the suggestion. Just to be clear, the configuration you're suggesting is

```
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
    forward-char
    end-of-line
    vi-forward-char
    vi-add-eol
)
```

Is this correct?

When I use this configuration, and the example above, `A` places the cursor in insert mode immediately after the `o` in `echo`. Is there a configuration that I should use that will make it so `A` places the cursor after the `H` in `$PATH`?

**Comment by jeffreytse** [comment]
Hi @gotgenes , the configuration you provided is correct. For choosing the suggestion, you can use `$` to instead of `A` after you setting with the configuration cleared.

**Comment by jeffreytse** [comment]
Hi @gotgenes 

I’m very sorry, I misunderstood your issue, and it's not about choosing the auto-suggestion or not, just about the wrong cursor position. Now this issue has been addressed and fixed, please update your plugin to the latest version.

Thanks and regards

**Comment by gotgenes** [comment]
@jeffreytse Thanks for following up! Yes, sorry, I probably could have made the issue clearer.

Confirmed fixed in the latest version!
