### ISSUE TITLE
Cursor mode not changing in ST

### ISSUE THREAD

**Issue by weisbrja** [jeffreytse/zsh-vi-mode#84]
# Reproduce

This bug **only occurs** when using [ST](https://st.suckless.org/) (the simple terminal from suckless).
To reproduce, simply put the following line in your `.zshrc` (sourcing the plugin in a different way might also work for reproducing this bug, but I have only tested sourcing it like this):
```zsh
source '/usr/share/zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh'
```

# Result

The cursor mode is not changing from block to line when switching between normal and insert mode.

# Expected behavior

The cursor mode should change from block to line when switching between normal and insert mode.

**Comment by jeffreytse** [comment]
Hi @weisbrja 

Thanks for the reporting. Could you try this command `echo $TERM` and tell me the result?

Thanks and regards

**Comment by weisbrja** [comment]
Output for `echo $TERM`:
```
st-256color
```

**Comment by jeffreytse** [comment]
Hi @weisbrja 

Thanks for your patience. This issue has been addressed and fixed, please update your plugin to the latest version. And also welcome to star this project for further udpates in the future. : )

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @weisbrja, Is this issue settled down?

**Comment by weisbrja** [comment]
@jeffreytse Yes, this issue has been resolved.
