### ISSUE TITLE
read-only variable: ZVM_NAME

### ISSUE THREAD

**Issue by mskar** [jeffreytse/zsh-vi-mode#9]
What does this mean?

```
~/.zsh-vi-mode/zsh-vi-mode.zsh:100: read-only variable: ZVM_NAME
```

How can I avoid this message upon shell startup?

**Comment by jeffreytse** [comment]
Hi @mskar 

Could you provide the instructions about how you loaded this plugin?

Thanks and regards

**Comment by mskar** [comment]
I cloned and sourced the plugin:
```sh
git clone https://github.com/jeffreytse/zsh-vi-mode.git $HOME/.zsh-vi-mode
source $HOME/.zsh-vi-mode/zsh-vi-mode.plugin.zsh
```
I think I will have to use the process of elimination to see which line(s) in [my .zshrc](https://github.com/mskar/setup/blob/main/.zshrc) is/are causing the problem.

**Comment by jeffreytse** [comment]
Hi @mskar 

👍 You are right, to use the process of elimination to see the promblem. Any progress, please share to here, in case of it could help other people.

Thanks and regards

**Comment by GerardKetuma** [comment]
I'm also having this issue. Get this on the terminal when I run `source`
`~/.oh-my-zsh/custom/plugins/zsh-vi-mode/zsh-vi-mode.zsh:105: read-only variable: ZVM_NAME`

Line 105 of zsh-vi-mode.zsh is below:
`typeset -gr ZVM_NAME='zsh-vi-mode'`

It seems that ZVM_NAME cannot be set for some reason.

**Comment by mskar** [comment]
Could it be an OS-specific issue?
@GerardKetuma, do you also use MacOS?
https://opensource.apple.com/source/zsh/zsh-65/zsh/Doc/help/typeset.auto.html

**Comment by GerardKetuma** [comment]
> Could it be an OS-specific issue?
> @GerardKetuma, do you also use MacOS?
> What if we remove the `-r` option from line 105?
> `typeset -g ZVM_NAME='zsh-vi-mode'`
> https://opensource.apple.com/source/zsh/zsh-65/zsh/Doc/help/typeset.auto.html
> If that doesn't work, maybe we can use `export` instead of `typeset` to set `ZVM_NAME`?

@mskar Yes, I'm using Mac OSX.

Tried removing the `-r` option but still got the same error.

**Comment by jeffreytse** [comment]
Hi, @GerardKetuma @mskar 

Many thanks for you guys reporting this issue and I'm so sorry for the inconvenient. Could you provide more details for me to dig this problem? Currently I have no way to reproduce it.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @GerardKetuma @mskar 

The commit (cd50109) has added a new feature to avoid sourcing this plugin multiple times. Welcome to update to this plugin and give some feedback.

Thanks and regards

**Comment by mskar** [comment]
@jeffreytse, I think this change fixed the issue. I will close the issue now.
@GerardKetuma, if you still get the message, please let me know and I can reopen this issue.
