### ISSUE TITLE
Using the plugin breaks fzf's ctrl+r bind.

### ISSUE THREAD

**Issue by ftpd** [jeffreytse/zsh-vi-mode#90]
It doesn't matter if I source zsh-vi-mode before or after fzf stuff, ctrl-r is somehow taken for `"^R" history-incremental-search-backward`. Even if I manually bind my ^R *after* loading the plugin (via `bindkey "^R" fzf-history-widget`) it still doesn't work. What am I doing wrong?

**Comment by jeffreytse** [comment]
Hi @ftpd  

For this issue, you can read [here](https://github.com/jeffreytse/zsh-vi-mode#execute-extra-commands) or refer to #24. And welcome to star this project for further updates in the future. : )

Thanks and regards

**Comment by ftpd** [comment]
Right, that works, thank you!
