### ISSUE TITLE
ZVM_VI_ESCAPE_BINDKEY not working for '^J' anymore

### ISSUE THREAD

**Issue by kyazdani42** [jeffreytse/zsh-vi-mode#93]
## General infomation

zsh-vi-mode 0.8.2
archlinux
alacritty

## Problem description

title is descriptive, i used '^J' (control j) for escape, after updating, stopped working.
This happened since ba3493c

## Reproduction steps

set the variable to '^J', it doesn't escape as expected

## Expected behavior

escape :)

**Comment by jeffreytse** [comment]
Hi @kyazdani42 

Thanks for the reporting. I will try to fix this issue as soon as possible.

Thanks and regards.

**Comment by jeffreytse** [comment]
Hi @kyazdani42,

Thank you for your patience, I have been busy during this period. Now this problem has been solved successfully. Please update your plugin to the latest version.

Thanks and regards.

**Comment by jeffreytse** [comment]
Hi @kyazdani42 

Could we close this issue now?

Thanks and regards

**Comment by kyazdani42** [comment]
looks fixed indeed, thanks :)
