### ISSUE TITLE
`a` `i` will not enter the insert mode occasionally, but `A` `I` will. And surround command `S` also broken

### ISSUE THREAD

**Issue by androidfans** [jeffreytse/zsh-vi-mode#94]
This issue happens occasionally.
I have found this issue after updating plug on 19th April。
My last update date is 17th March. So maybe the commits in this period caused this issue。

Some related  settings in my .zshrc below
```bash
zinit ice depth=1
zinit light jeffreytse/zsh-vi-mode
set -o vi
bindkey '^@' autosuggest-accept
```

**Comment by androidfans** [comment]
BTW, I have just updated to ubuntu20.04 recently. Don't know if it affected

**Comment by jeffreytse** [comment]
Hi @androidfans 

Thanks for your reporting, this issue is quite weird, could you provide me your dotfiles to do the investigation?

Thanks and regards

**Comment by androidfans** [comment]
@jeffreytse  Has sent to your mail from rejectliu@gmail.com
BTW, i am using the powerlevel10k theme. it can make your prompt load fast without any delay
https://github.com/romkatv/powerlevel10k

**Comment by jeffreytse** [comment]
Hi @androidfans,

Currently I'm busy, I will try to settle this issue as soon as possible, please be patient.

Thanks and regards

**Comment by androidfans** [comment]
@jeffreytse  just relax. I have reverted the zvm version. It is not block my work. feel free to fix it in a proper time

**Comment by jeffreytse** [comment]
Hi @androidfans 

I still can't reproduce this issue, it would be better to have some additional instructions for me to investigate this issue further.

Thanks and regards

**Comment by androidfans** [comment]
![动画](https://user-images.githubusercontent.com/6452650/118088498-c21f6c80-b3f9-11eb-9c5a-a5a2aa30a3c2.gif)
I have found a way to repro this bug in high probability.
step 1 : use esc enter normal mode
step 2 : use hhhhh go to the start of the line.
step 3:  kick hhhh in high speed
step 4: then `a` and `i` will not bring me into insert mode even after press enter to go to next command.

**Comment by androidfans** [comment]
![第二个](https://user-images.githubusercontent.com/6452650/118100534-2695f800-b409-11eb-891d-fe9a080851b0.gif)
Another  way to repro this. 
step is 
1. move to the end
2. repeat some `b` quickly
3. `a`

**Comment by jeffreytse** [comment]
Hi @androidfans 

Thanks for the useful informations. Currently this issue has been addressed and settled down, please update your plugin to the latest version and check again.

Thanks and regards

**Comment by androidfans** [comment]
@jeffreytse Amazing. you are so efficient! it's not repro on my machine

**Comment by jeffreytse** [comment]
@androidfans You're welcome, I hope you have a good experience on this plugin. : D
