### ISSUE TITLE
Grep error on every command after enabling this plugin

### ISSUE THREAD

**Issue by juanda1306** [jeffreytse/zsh-vi-mode#97]
## General infomation

- Terminal program: Alacritty
- Operating system: Manjaro Linux 5.4.114-1
- ZSH framework: none, manual installation (Also tried installing the AUR package)
- ZSH version: 5.8
- ZVM version: 0.8.3

## Basic examination

- [x] I have read through the [README](https://github.com/jeffreytse/zsh-vi-mode) page
- [x] I have the latest version of zsh-vi-mode
- [x] I have tested with another terminal program 

## Problem description

Every time I run a command I get a message saying
```grep: (standard input): binary file matches```
and then the actual output of the command I ran

## Reproduction steps

1. Running any command triggers the message

## Expected behavior
Not showing any grep message

**Comment by jeffreytse** [comment]
Hi @juanda1306 

This plugin has no using any `grep` commands. I think it's something wrong on your environment. Could you provide me more details? So that I can help you settle it down. And welcome to star this project for further updates in the future.

Thanks and regards

**Comment by jeffreytse** [comment]
Hi @juanda1306

Is this problem not reproduced after disabling this plugin?

Thanks and regards

**Comment by juanda1306** [comment]
Hi @jeffreytse. Yes, the problem goes away after disabling the plugin. Maybe you could check my [.zshrc](https://gitlab.com/juanda1306/dotfiles/-/blob/master/.zshrc) to see if there is any setting or any other plugin conflicting with zsh-vi-mode?
Thanks

**Comment by jeffreytse** [comment]
Hi @juanda1306 ,

Thanks for providing me your `.zshrc` file, could you comment some of your plugins and try again to check whether there are conflicts of plugins?

Thanks and regards

**Comment by juanda1306** [comment]
I commented out all of them, one by one, and I foud out that commenting out either zsh-vi-mode or [alias-tips](https://github.com/djui/alias-tips) solves the problem. Commenting any of the other plugins had no effect, so I guess it's an icompatibility between the 2 I just mentioned.

**Comment by jeffreytse** [comment]
Thanks for the useful information, I will have a future test. Once I get any progress I will comment here.

**Comment by juanda1306** [comment]
Okay, thanks!!!

**Comment by jeffreytse** [comment]
Hi @juanda1306 

Firstly, thanks for your patience. I have checked this issue, it is a bug on the plugin [alias-tips](https://github.com/djui/alias-tips). And I have submitted a PR to that project to fix the grep error. Once the PR is merged, this issue should be settled down perfectly.

Thanks and regards

**Comment by juanda1306** [comment]
Nice, thanks!!!

**Comment by jeffreytse** [comment]
Hi @juanda1306 

The PR has been merged, please update your [alias-tips](https://github.com/djui/alias-tips) and try again.

Thanks and regards

**Comment by juanda1306** [comment]
Yes, now everything works fine, thanks!!!
